### ISSUE TITLE
New draft skeleton + model

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/min_wage_rent#109]
EDIT by @santiagohermo: We are broadening the goals of this task, which is now tracked by #107. In here we will:

- Start over with the draft, following [this structure](https://github.com/diegogentilepassaro/min_wage_rent/issues/109#issuecomment-877959050)
- Add model @santiagohermo has been thinking about in #95 to it

Opened branch `#109_new_draft_skeleton` for related work.

----

[Goals]
Plan the write-up of the next draft and obtain a roadmap with a checklist of the sections and the ideal figures and tables to add in each section. 

[Output]
- A chronological list of sections, with titles. For each section, a list of tables and figures that will live there. Ideally, we could even have a sentence explaining the pitch and aim of each section and object within. 

[Notes]
- Based on the output of this issue we will open the necessary tasks to build the objects that will populate the draft. We will track those tasks  in #107, so the output of this issue is the main input of #107.

**Comment by santiagohermo** [comment]
Very cool paper on the incidence of the Los Angeles' minimum wage: https://www.nber.org/papers/w28966

> Using a novel data set from a multi-year price survey, our analysis shows that the incidence of Los Angeles City’s higher minimum wage fell on customers in high-income neighborhoods, and on landlords and restaurant owners in low-income neighborhoods. We further show that the mix of responses at restaurants subject to the LA City minimum wage, including price increases, menu changes, and restaurant closures, was affected by proximity to restaurants subject to the lower California State minimum wage.

fyi @diegogentilepassaro @gabrieleborg

**Comment by santiagohermo** [comment]
See https://github.com/diegogentilepassaro/min_wage_rent/issues/95#issuecomment-912997222 for some takeaways on the model from issue #95.

**Comment by santiagohermo** [comment]
Note: I left the current intro, data section, and empirical strategy sections, as they might be helpful when re-writing

**Comment by santiagohermo** [comment]
I updated the README with suggestions to write the paper, it now looks like [this.](https://github.com/diegogentilepassaro/min_wage_rent/blob/09778bdf9ef6946c0bccf8fbb145f1496b4fa643/README.md)

fyi @diegogentilepassaro

**Comment by santiagohermo** [comment]
Continues in #116

**Comment by santiagohermo** [comment]
Summary: in this section we added the model from #95 to the paper, and implemented the skeleton in [this comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/109#issuecomment-877959050). Review in #109
