### ISSUE TITLE
Develop main function to estimate model + update main figures

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#111]
This issue is tracked by #107. In here, we will:

1. Write a function that estimates the distributed lag model and saves results to a csv or a tempfile or leaves them in memory. We want the function to be flexible so that we can run many estimations in loop and append all results in the same dataset.
2. Use function to update `analysis/first_differences`, which should now produce table 1 for static model and main dynamic model figures, following [the slides](https://github.com/diegogentilepassaro/min_wage_rent/blob/61ef6f1b3314b758f6d606fd84d353caf92b77e1/paper_slides/slides/long_slides.pdf)

Issue #113 will update other estimations in `analysis` following the structure developed here.

**Comment by diegogentilepassaro** [comment]
Starting here @santiagohermo!

**Comment by diegogentilepassaro** [comment]
Created branch `issue_111` and started out with some housekeeping. I deleted:

- `analysis/estimates_benchmark'
-  `analysis/event_size_robustness'
-  `analysis/estimates_benchmark'
-  `analysis/estimates_benchmark'
-  `analysis/estimates_benchmark'
-  `analysis/estimates_benchmark'

**Comment by santiagohermo** [comment]
> Notes:
> 
> * Opened branch `#111_main_results` for related work

Fijate que ya había una branch abierto querido @diegogentilepassaro. La podes borrar?

**Comment by diegogentilepassaro** [comment]
Hola @santiagohermo! No veo ninguna:
<img width="1399" alt="Screen Shot 2021-09-07 at 11 25 28 AM" src="https://user-images.githubusercontent.com/20582494/132371057-324c6b04-cfe4-4735-baee-fe4171842e32.png">

**Comment by santiagohermo** [comment]
Oops, gracias por chequear @diegogentilepassaro! Parece que nunca la publiqué (quedó local en mi machine nomás). Borré esa nota del [opening comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/111#issue-988203445).

**Comment by diegogentilepassaro** [comment]
Update: I finalized my first pass of the function `estimate_dist_lag_model`. Code lives in `analysis\distributed_lag_estimation` and there I estimate 4 models that should cover all we need for creating our [famous static table](https://github.com/diegogentilepassaro/min_wage_rent/issues/108#issuecomment-852464324) and our [dynamic plots](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2393-slides_lunch/paper_slides/slides/long_slides.pdf) (see slide 34). 

A few important comments and notes:
1. So far I have only computed the cumulative summed coefficients starting from 0. We can add it easily later, but computing it starting from -6 is a bit weird for at least 3 reasons:
  - The path does not constitute a causal effect as we are not imposing the "no pre-trends assumption".
  - It is a little bit arbitrary: why don't we start from another period like -1? 
  - Clutters the code and will clutter the figures. 
2. At 0 the cumsum is just the sum of the dynamic variable at 0 (usually `exp_ln_mw`) and the static variable at 0 (usually `ln_mw`).
3. The code handles the static case by setting `w = 0`.
4. The code handles the case of using only a variable of interest by setting `stat_var = dyn_var`.
5. The output for the dynamic case looks like:
![Screen Shot 2021-09-07 at 12 35 05 PM](https://user-images.githubusercontent.com/20582494/132380294-3154c5ba-8ead-4a2a-a114-d71dce1b6378.png)
6. The output for the static case looks like:
![Screen Shot 2021-09-07 at 12 37 34 PM](https://user-images.githubusercontent.com/20582494/132380586-11c6e42f-6761-4c87-9735-d8dd0f83fa5a.png)
7. A model of `exp_ln_mw` on `ln_mw` looks like (note that it requires that `stat_var = dyn_var`)
![Screen Shot 2021-09-07 at 12 38 34 PM](https://user-images.githubusercontent.com/20582494/132380710-3aa60fd4-4e10-4055-8dc9-a400f9961d2c.png)
8. A model for the dynamics of `ln_mw` controlling, on top of for the economic controls, for `exp_ln_mw` looks like:
![Screen Shot 2021-09-07 at 12 40 00 PM](https://user-images.githubusercontent.com/20582494/132380895-40178568-f554-4a2d-a7b8-e474cdd2af42.png)

I suggest the following plan:
1. @santiagohermo take a quick look at `analysis\distributed_lag_estimation` and makes sure that estimates are correct and that the program handles the cases that we want.
2. We open a task for @gabrieleborg to create scripts that use the output of `analysis\distributed_lag_estimation` to create the static table and our dynamic figures.
3. In parallel, I can work on estimating other models (maybe a directory for AB, or for the levels, or for the county-month data).
4. I can review @gabrieleborg work when he is through. and then add  the computation of a few hypothesis test that we used to care and we can add y-means to the output to embelish the figures. 

What do you guys think?

**Comment by santiagohermo** [comment]
[Thanks](https://github.com/diegogentilepassaro/min_wage_rent/issues/111#issuecomment-914464475) @diegogentilepassaro! That output looks very cool. I made a few changes in the commits above, including:

- move function to library,
- rename folder,
- unignore estimation csv results,
- add a couple of useful pvalues and sample size

I'll add the tables later

**Comment by diegogentilepassaro** [comment]
Thanks @santiagohermo!

I think that now the .csv is unignored twice! See line 14 [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/638cbb51339c50c799ad769e79cb2d4239312343/.gitignore)

**Comment by santiagohermo** [comment]
You're right @diegogentilepassaro. I think that I didn't see them before because I changed the name of the folder (probably better to avoid it). Feel free to drop the duplicate!

**Comment by santiagohermo** [comment]
Agregué estructura para armar la table @diegogentilepassaro. Fijate como la ves!

(Nota: el model de exp mw on statutory mw tiene muchas observaciones. Hay que tirar los leads and lags para que matcheen)

**Comment by diegogentilepassaro** [comment]
@santiagohermo I have made a few commits in which I:
- Fixed a mistake in the computation of the cumulative sums.
- Output in a single file the estimation of all dynamic models.
- Build flexible functions to estimate the main figures and output them.
- Changed the table fill so that it happens within a make.py framework. 

Our main figures (with clustering at the state level) now look like the following:
**ln mw only**
![Screen Shot 2021-09-08 at 12 48 05 PM](https://user-images.githubusercontent.com/20582494/132550953-53caaaab-3bea-42bb-8e4d-a933901479b5.png)

** Exp ln mw only**
![Screen Shot 2021-09-08 at 12 48 20 PM](https://user-images.githubusercontent.com/20582494/132550987-c7d6c75d-c3ca-4069-bfaf-1b588d2fca03.png)

**Exp ln mw Both**
![Screen Shot 2021-09-08 at 12 48 52 PM](https://user-images.githubusercontent.com/20582494/132551096-a79239c9-dcbf-4994-897f-4e47ffb08a58.png)

**ln mw Both**
![Screen Shot 2021-09-08 at 12 49 04 PM](https://user-images.githubusercontent.com/20582494/132551121-216e42b4-3c6f-4f29-aaf3-f32de46c4bf0.png)

I will send to PR for @gabrieleborg to take a look at this but also feel free to check if you like the handling of the dynamic estimates and the figure building.

**Comment by diegogentilepassaro** [comment]
Continues in #117!

**Comment by santiagohermo** [comment]
Summary: In this issue we created a function to estimate models and settled on a structure for estimation, figure and table construction. Changes merged to master in #117
