### ISSUE TITLE
Add Wages and Employment data

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#16]
**[Goal]**
Add data on wages and employment at the most disaggregated level.

**[Notes]**
1. We have in mind to use the [Quarterly Census of Employment and Wages](https://www.bls.gov/cew/) as main source.
2. We should consider adding data from the census for available years as well.

**Comment by diegogentilepassaro** [comment]
I've started working in this task. The data should be downloaded form [this website](https://www.bls.gov/cew/downloadable-data-files.htm) and we should use the NAICS-Based Data Files. That website also contains the links to access data guides and dictionaries. 

First some comments on things that we have to decide:

- The data is available in several formats. I went over all of them and the useful ones are:

    1. County High-Level: for each year download comes a file for each quarter within that year. For each file we have all counties and all MSAs separated into 12 very broad industry codes. Contains employment at the monthly-county-industry level, number of establishments  at the quarter-county-industry, and average weekly wage within each quarter-county-industry. Does not contain geo unit FIPS code. 

    2. CSVs by area quarterly: for each year download we have one file per geo unit (state, county or MSA) containing FIPS code and unit name in the name of each file.  Within each file there is information on all quarters for the same variables as in 1. but there is also some extra variables (potentially useless) and (crucially) area FIPS code for each geo unit. 
![Screen Shot 2020-04-03 at 11 56 08 AM](https://user-images.githubusercontent.com/20582494/78381309-2f2fc400-75a3-11ea-804f-53f772b8ebcf.png)

   3. CSVs by industry quarterly: same as 2. but within each year download there is a file by detailed industry code (hundreds of categories) containing information on that industry code activities for all quarters for each county and MSA.  Some examples below. 
![Screen Shot 2020-04-03 at 12 05 09 PM](https://user-images.githubusercontent.com/20582494/78381464-6605da00-75a3-11ea-8ef0-0424b7f0a1d2.png)

- My hunch is that we need to create a crosswalk between county names and area FIPS codes using files in 2. or 3. and then we will probably be OK using files from 1. but adding the area FIPS codes through the crosswalk. 12 industry codes seems good enough although we can use files from 3. for some particular industries that we think relevant (like all that have an average weekly wage of less than something).  Something to discuss but we probably will need to upload to our data files from 1. for sure and potentially some from 3.

**Comment by santiagohermo** [comment]
Thanks for that summary @diegogentilepassaro! Those data look great.
Looking forward to talk about them in the code.

**Comment by diegogentilepassaro** [comment]
@santiagohermo I am not sure how we should distribute this task (I am happy to talk about that anytime), but anyways I forgot to make a note of what the deliverable of this task should be. I gave this some thought and I believe that it should be four mini-datasets:

1. County-month: Containing employment.

2. County-quarter:Containing employment (that also comes at the quarter), establishments count, and average weekly wage. 

3. County-month-industry_code: Containing employment. 

4. County-quarter-industry_code: Containing employment (that also comes at the quarter), establishments count, and average weekly wage. 

Some important notes: 

- Seems that the other variables will never be needed. 

- Unfortunately we don't have data on the hours worked, so at a later step, we will have to compute the hourly wage for panels 2. and 4. assuming that people work 40 hours a week or something like that. 

- All 4 panels are needed. Combining 1. and 3. we will know what is the share of employment that belongs to each industry code in each month, so a measure of the share of workers that make a given wage (as wage is particular to a given industry). With panels 2 and 4. we will be able to add wages at the quarterly level and we will then have which wage they make in each quarter-county-industry.

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro ! I am happy to share work here in whichever way you prefer. I'll probably be able to work on this late in the upcoming week or weekend.

Regarding to your last point: 

> - All 4 panels are needed. Combining 1. and 3. we will know what is the share of employment that belongs to each industry code in each month, so a measure of the share of workers that make a given wage (as wage is particular to a given industry). With panels 2 and 4. we will be able to add wages at the quarterly level and we will then have which wage they make in each quarter-county-industry.

That is very useful information. In fact, Dube et al (2019) argue that the effect of the MW is heterogeneous in the industry dimension.

**Comment by diegogentilepassaro** [comment]
Very nice @santiagohermo! I will start working on #24 and later #26 so probably it is a good idea if you take over this one, as now it is clear what we should do.

**Comment by santiagohermo** [comment]
I was finally able to work on this a bit. I created a python script in the drive to download the data summarized [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/16#issuecomment-608528231) and its currently downloading. I will process it later to construct panels in the spirit of [this](https://github.com/diegogentilepassaro/min_wage_rent/issues/16#issuecomment-612150342)

**Comment by santiagohermo** [comment]
I downloaded the data in the server @diegogentilepassaro. 
![image](https://user-images.githubusercontent.com/45404755/79460790-52a33780-7fc3-11ea-8033-ff11e8016899.png)

It's quite heavy, and processing probably won't be fast! So I suggest we create a stable version of the tables [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/16#issuecomment-612150342) stored in the `drive/base_large` . Unless you disagree, that will be my next step here.

**Comment by diegogentilepassaro** [comment]
Thanks @santiagohermo! I just reviewed your work and it looks great.

Two things: 

- We should commit to the repo the code and docs folder within raw_data/qcew along with the readme file. It is tricky because we don't want to commit the drive but we should maybe then consider having a copy of raw_data outside the drive that we commit only code, docs, and links or something like that. What do you think? 

- I have reassigned myself this task together with you so feel free to direct me to do some of the processing in a way that makes sense so that we don't double-work and we can get this done quicker.

**Comment by santiagohermo** [comment]
Thanks for the help @diegogentilepassaro! 
I think the docs it's ok to keep in the drive only, since they are just downloads of the relevant website. I agree on adding the code! I will create a branch and add a new step previous to `base` to store any code necessary to get the raw data.

**Comment by santiagohermo** [comment]
I added code to build the raw data above. It runs with python 3, thus we cannot use the `make.py`. I figured out how to create a simple log file to replace that. I think this should sufficient for the purposes of getting the data.

Currently I'm scraping again. Once I'm done, I will commit the log file.

**Comment by santiagohermo** [comment]
On second thoughts I added docs and readme to the repo, and left only data in the drive.

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro Guys how are we on this?

**Comment by santiagohermo** [comment]
All I've done so far is write down a small chunk of code to get the data @gabrieleborg. [This](https://github.com/diegogentilepassaro/min_wage_rent/tree/fa1219b81e0edee530fe50a7ef2c398e67975d5a/raw/qcew) is the folder where it lives. The data is downloaded in the server.

Next steps are to understand the structure of the data and start processing it.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg and @santiagohermo habemus panel!

I've created under base some code that processes the QCEW data and creates a county-quarter-industry panel from 2010 to 2019. 

In order to do that I have restructured \base so that we don't have to run all code together. I will keep moving with this task and write the derive stage and merge to the main panels after merging #29 to master.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg and @santiagohermo as in this task I have to create a county-quarter-panel I will also take care of fixing the geo codes here.

**Comment by santiagohermo** [comment]
Note @diegogentilepassaro @gabrieleborg. I added some mw data for a city in california that the original dataset was missing ([source](https://www.ci.emeryville.ca.us/1208/Living-Wage-Ordinance))

**Comment by santiagohermo** [comment]
Thread continues in PR #32
