### ISSUE TITLE
Simulation: Build fake dataset and test event studies

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#17]
**[Overview]**
This issue is a follow-up of #11 and, in particular, a suggestion of Jesse Shapiro to understand how the event-study design in first difference would look like.

**[Goal]**
Understand how the first-difference event-study design works and should look like in case minimum wage changes actually increase rents.

**[Steps]**
1. Simulate rents, minimum wages, and house values data per geographic unit. Consider having two kinds of geographic units in which the effect of minimum wages would be different.
2. Try out a first-difference event-study design on the simulated data.

**[Notes]**
- House values should be computed as the present value of discounted rents (plus a random shock?)
- Think about anticipatory effects in house values.

**Comment by diegogentilepassaro** [comment]
@santiagohermo I think that now we are ready to tackle this task. Now that the last event methodology is more reliable and we have smooth 24 window period event studies for the same type of housing for both rental and listing prices it seems that we can compare our simulations with our results.

For example, for the type of house SFCC, the dynamics of rent per square foot look like:
![Screen Shot 2020-04-18 at 10 17 31 AM](https://user-images.githubusercontent.com/20582494/79640125-d4c76380-815d-11ea-9f10-b5a8e4b967f6.png)
and for listing price it looks like:
![Screen Shot 2020-04-18 at 10 17 11 AM](https://user-images.githubusercontent.com/20582494/79640131-dc870800-815d-11ea-9c56-6228f3505649.png)

Is the second plot what a simulation of listing price based on PDV of rent payments will look like if the rent payment change is the one that we computed in the first plot? To answer that question we will need to assume something about the moment of the announcement of the MW change. Is what we see consistent with some reasonable assumption? 

Possible assumptions to simulate:

1. The exact dynamics of rent prices around MW changes is know ex-ante.

2. The change is only known to happen 12 or 24 months before. 

3. The change takes landlords by surprise. 

Let me know your thoughts and we can start playing around soon!

**Comment by santiagohermo** [comment]
Per call today, in this task we should use the existing dataset and simulate only rents and house values. With the simulated data, we should 
- try out our "last" methodology to compare with our results, and 
- try out the first-differences design.

**Comment by santiagohermo** [comment]
In this branch I will simulate a fake dataset to try our "last" event study specification. This dataset will also be useful to test other specifications in the future

**Comment by santiagohermo** [comment]
I'm done with the first simulation exercise @diegogentilepassaro @gabrieleborg ! This is a simple case with zipcode and year month fixed effects and here our event study seems to work

- [This](https://github.com/diegogentilepassaro/min_wage_rent/tree/692ad4b191fea15fbe1f934728f6ee4eb71cb9e1/derived/simulation) is the derived folder. I added a readme where I explain how I generate the rent variable
- [This](https://github.com/diegogentilepassaro/min_wage_rent/tree/692ad4b191fea15fbe1f934728f6ee4eb71cb9e1/analysis/simulation) is the analysis folder. See the [output](https://github.com/diegogentilepassaro/min_wage_rent/tree/692ad4b191fea15fbe1f934728f6ee4eb71cb9e1/analysis/simulation/output).
   - Briefly, in rent1 the minimum wage has no effect, whereas in rent2 the minimum increases a 10% of the estimated change in income due to the MW in a household with 2 MW earners. Our specification correctly finds no effect with rent1 and a significant effect with rent2

**Comment by santiagohermo** [comment]
An update here @diegogentilepassaro @gabrieleborg. I added some rent variables with level mw changes (full explanation [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/derived/simulation/README.md), data manifest [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/derived/simulation/output/data_file_manifest.log), code [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/derived/simulation/code/simulate.R))). Briefly,

- `rent1` = zipcode FE, year-month FE, shock
- `rent2` = zipcode FE, year-month FE, **%mw effect**, shock
- `rent3` = zipcode FE, year-month FE, **level mw effect**, shock
- `rent4`, `5` and `6` are defined analogously but add a state-specific trend.

The %mw effect is set to 5% of the estimated increase in income using `dactual_mw`. The level effect is set to $30. I also lowered from $100 to $75 the standard deviation of the shock.

**Results**

Full output is [here](https://github.com/diegogentilepassaro/min_wage_rent/tree/e87f1f3e49e885d6e7133716228f65412ef96906/analysis/simulation/output). As per [these lines](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/analysis/simulation/code/last_preclean.do#L17-L18), I am dropping all zipcodes without events.

I noticed that the event studies have a really hard time finding the true level effect of $30 in the case of `rent3` and `rent6`. Specially the 6-months estimates look quite weird, suggesting a negative effect in the case of state#yearmonth(e.g., [rent3-state-trend-w6](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/analysis/simulation/output/last_rent3_w6_state-trend.png), [rent3-state#yearmonth-w6](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/analysis/simulation/output/last_rent3_w6_state_x_time.png)). The state by yearmonth FE with 12 month window look best for `rent3` and `rent6` (e.g., [rent3-state#yearmonth-w12](https://github.com/diegogentilepassaro/min_wage_rent/blob/e87f1f3e49e885d6e7133716228f65412ef96906/analysis/simulation/output/last_rent3_w12_state_x_time.png))

This may be related to the under-identification issue discussed by [Jaravel and Borusyak](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2826228).

**Next steps**
- Simulate housing values
- Send to PR and, after making sure the code is right, try different specifications on the simulated data.

**Comment by diegogentilepassaro** [comment]
Thanks for the update @santiagohermo! Once I am through with #34 I will take a deeper look here :D

**Comment by santiagohermo** [comment]
Thread continues in #42
