### ISSUE TITLE
Amenity Index

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#27]
**Goal**

Understand  how to build , and create, an index for amenities that allows to capture local changes in response to MW treatments so to pin down the endogenous sorting of people across zipcodes. This measure should account for the fact that the event-study specification is already rich of FE controlling for local dynamics. Clarify the role GPS location data can play in mapping zipcode residents' preferences for various type of amenities, and how this can contribute to the construction of the aforementioned index. 

**Steps**

1. Literature Review:

   -   How amenities are measured, and at which geographic and temporal level. 
   -   How spatial patterns can identify people preferences

2. Identify simple/reproducible facts that can test the main assumptions to be validated

3. Start investigating (also on a sample) the potential dynamics it is possible to quantify

**Comment by gabrieleborg** [comment]
Morning Guys! @diegogentilepassaro @santiagohermo 

Points 1 and 2 of the Steps list are being investigated both with you during our calls, and  individually I am keep reading papers and ideas. Since we need a boost for this issue I am anticipating step 3, which ideally will inform us also on the previous ones in a feedback loop.

I started creating the code to process the GPS data in order to create some initial potential measure for amenities. The data comes in Points-of-interest (POI)-monthly pattern cross-sections, that joined together create the monthly panel. I put the raw data in our Gdrive, in the subfolder `SafeGraph` along with all the complementary files that are needed (e.g. each POI info such as the industry categorization, that comes in a different file). 

As a first pass, I am focusing on computing the median income of visitors for each zipcode's _restaurants and eating places_ NAICS 4-digits categorization ([link](https://www.naics.com/code-search/?naicstrms=7225)). This includes therefore, bars, cafeterias and fast food as well. 
To do this, I organized the code in 2 scripts living in `base/code` that take care of the following steps: 

1. For each monthly file, extract the raw data, remove unused variables, normalize visits and compute the median income of each POI visitors. The visit normalization is done in order to account for sample bias (i.e. certain geographies may be over-represented) and temporal growth of the sample of devices tracked. I followed what has been identified as one of the best practice to normalize SafeGraph Data in the community of researchers using it, but this is not the only way to do it and we could talk about it. Specifically:  

    - for every POI-month, we observe number of visits and number of unique visitors. The first assumptions is to assign to each unique visitor the same number of visits (e.g. if place x has 100 visits and 75 unique visitors, we'll have that each visitor has done on average 1.33 visits). 

    - We then "distribute" this number of visits to each census block group of origin observed (e.g. if block group y sends 10 people, then it'll have 13.3 visits to place x). 

    - We then weight each block group of origin visits by a multiplier which is the ratio between the census block group population in the 2012-2016 acs5 and the SafeGraph sample numerosity for the same census block group in the month under analysis. Importantly, we weight all the untraced visits by the multiplier computed for the POI's county. As I was saying, other people uses the state level average, but I think the POI's county gives a fair average of the visitors in a place (we also may have a way to test the impact of this assumption on more recent data that comes with less privacy restriction, more on that will follow).

    - Finally, we use the census block group of origin median income as the visitors' characteristic (and once again we use the county average for untraced visits) and we  compute, for each POI, the weighted average of this variable, weighting for the number of visitor sent by each census block group)

This gives us a series of POI-month level panels that I temporarily  save in `base/temp/`. 

2. The second step (not pushed yet) involves taking the temporary POI-month level files and aggregating them at the zipcode level. This returns a zipcode-month panel where we'll have information on the number of POIs in each geounit and the weighted average of the visitor's characteristics, weighted by the number of visits to each place (so that places receiving a lot of visits will count more). As mentioned above, this file will only account for restaurants and eating places right now, but we can do this for all sorts of establishments either in separate files or in one file together. This output(s) will be initially placed in `base/output/`, even though if it becomes to big we can think of creating some sort of `base_large` in the Gdrive similarly to `derived_large`. 

I tested the code only on one month  (on  a new branch called Issue27-Amenity-Index) because it will take a while on my laptop, so please could you make it run on the server so we can see whether there are errors or if it works smoothly already :D 
Please if you could test this soon it'll be great as I expect a considerable amount of work on this once we'll start experimenting with such data. Plus, it'll give us an initial sense of how long it will take to process this data.  Thanks!!!!!

**Comment by gabrieleborg** [comment]
@diegogentilepassaro  @santiagohermo 

With 74e046ca58c163f95d01df53affcdb30283bd701 I have optimized the function that computes the average visitors characteristics. I did that by replacing loops with faster apply functions and shifting, where  possible, from dplyr to data.table syntax. I have benchmarked the execution time for a single state in a single month and the time reduced by approx 70% on my laptop, but I couldn't test it on a whole month yet as I am finishing running the old version to extract another month I want to use for some bias correction and I don't want to lose the output. I added print commands stating the work in progress but I am not sure they work in batch mode, as I was saying I tested it in interactive mode only for the moment.

**Comment by santiagohermo** [comment]
The code has been running in the server for about an hour as of now. It seems to be working perfectly fine! Unfortunately, the `print` commands are not printing to the batch, so I can't tell the progress.

**Comment by santiagohermo** [comment]
Let me know when you have an update and want to run this again @gabrieleborg !

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro! sorry for the delay but I was figuring how to stabilize the sample in a consistent way, as I realized we only have the _universe_ of POIs starting in September 2019. This means that in months before that we can't directly know, when a POI shows up for the first time in a certain month, whether it was simply recently added to the universe or if it was already there but receiving 0 visits. This is very important to check: while running the code for parks (naics   712190) I discovered that in Dec 2019 they literally doubled the number of parks in the sample (from some 50k to around 100k). For this reason I adopted the following methodology: 
before aggregating at the zipcode-month level, I check that each POI I am using (for whatever naics category I am working on) appears **at least once** in each year of the sample, i.e. it has to show up in at least one month of 2017, 2018 and 2019. This is not perfect, but it stabilizes the number of underlying POIs used greatly. 

I just pushed such edits in the last commit, where I already changed the target naics code to 722513 for you to run @santiagohermo . These places are  labelled _limited service restaurants_ and it includes cafes, carryout restaurants, fastfood, pizza parlors, etc. I thought this could be an interesting category to start with as it captures a bit the kind of places people like to spend time during free time (i.e. brunches etc) and it could give us a nice picture of who is enjoying the neighborhood in a sense. I had already processed parks, and now I am working on a preliminary analysis...stay tuned!

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! It is unfortunate that the sample of places changes so much. I think your approach of checking it shows up at least once is a good place to start.

Now that I think about it, it would be nice to have two measures:
- **Composition-fixed measure**. Fix the POIs to some set (maybe those that show up in the first 6 months of 2017?). This would fix composition and will allow us to look only at the characteristics of people who go to those places.
- **Count measure**. Forget about the composition and just count places in a category by comparing to the last month of 2019.

With these two we could see whether the "quality" of places improves, and whether new places open up in a given zipcode. What do you think? (fyi @diegogentilepassaro)

Btw, code is running in the server!

**Comment by diegogentilepassaro** [comment]
@santiagohermo I think that what you describe is a great plan! We should aim to have two measures like that 😊

**Comment by gabrieleborg** [comment]
@santiagohermo that's indeed very good! 

-  **composition fixed measure**. Yes I think it's worth to try to fix POIs in that way as well. Let's see how these first round goes and and let's try that one! Also, I think we should refine the measurement of people characteristics in the following way: right now we compute, for example, the average income of visitors. But what can we can we say if, after a MW increase, we see a decrease in that number? Is it because more low-income people were visiting that place, or is it because less high-income people started going in certain places? I think a clearer measure to build would be shares. In this example I would compute the share of high-income people (say, people coming from block groups with median income higher than $100k) and the share of low-income people (say, people coming from block groups with median income lower than $30k). In this way we could look at the behavior of either or both of this measure and truly understand how the composition of visitors change. 

- **count measure** : this is indeed closer to what other people have done (e.g. Couture et al 2020), but we have to be very careful here with the composition effect: Do we see, say,  more nice restaurants in a given zipcode because they are opening more, or because SafeGraph is adding more restaurants to their sample? to do that we would need the _core poi_ dataset for each month, which we don't have. Still I think that we could definitely try that! And once we do that, it would then be possible to classify places from national brands by the quality of visitor overall (again, similar to Couture et al 2020): specifically, we could compute the average quality of visitors over all US to determine which places are visited by higher-income people, so that we could then say " in this zipcode, they now opened x number of high-quality places of this type", as Safegraph tracks a lot of national brands (restaurant chains, gyms, etc)

**Comment by gabrieleborg** [comment]
Morning guys! 

So after a day of fight I got some initial results over the first version of amenity index we discussed, meaning the median income of visitors. I computed that for two places categories: Parks and Similar Institutions (naics 712190) and Fitness and Recreational Sport Centers (naics 713940). The results are not very neat or clear, but I think there are signs of potential nice improvements. Let me explain how I did it exactly and why I think that's the case:

- As discussed, before aggregating at the zipcode-month level I restricted the sample to POIs appearing at least once in every of the 3 years of data we have (2017, 2018, 2019). This gave us a fairly stable sample size for each zipcode across all months in the panel. The zipcode-month panels are saved in `base_large/output/`.

-  In the derived stage, I added a script called `create_amenities_panel.R` where I pull together the various measures for each naics code in a single zipcode-monthly panel. The results is `amenities_csv` living in `derived/output` where each naics code has (for now) 3 columns: poi_count, total_visits and median income:
![image](https://user-images.githubusercontent.com/30894427/81942111-b2dbc800-95c7-11ea-9310-aff8f1bc1329.png)
This is merged with the `data_clean.csv` large file, before creating the balanced panels for each variable. 

- In order to keep things consistent, I then extended the balancing procedure introduced by @diegogentilepassaro to these new variable as well, creating baseline_panels that, for a given window size, have all non-missing observation in the window: 
![image](https://user-images.githubusercontent.com/30894427/81942781-912f1080-95c8-11ea-8b96-f87b7dad5272.png)
As you can see, I had to make the balanced panel start in 2017 clearly. 

- I then run the test_event_study scripts for the amenities index I had so far: 

**Average Income for Parks visitors**
![med_hhinc2016_712190_12_the_FEs_limit](https://user-images.githubusercontent.com/30894427/81943278-2cc08100-95c9-11ea-8010-4d74bf9601db.png)
This was difficult to interpret, as there's a lot of pre-trend. I do see a change in the trend right at the event, and this seems to persist as we augment the set of controls (which I think in this case are very important as states have very different visit patterns according to latitude). I think there might still be some data issue as there are sudden drops (see, for example after the t+3 period). 

**Average Income for Gym Visitors**
![med_hhinc2016_713940_12_the_FEs_limit](https://user-images.githubusercontent.com/30894427/81943850-e7e91a00-95c9-11ea-909b-31aa80e62361.png)
This I think is much clearer. I believe this is due to the fact that there are more gyms in the sample, plus they don't suffer geographic heterogeneity as much as parks and open air places in general. Unfortunately, the trends looks somehow opposite of what we would like: decreasing pre-trend that stabilizes around zero right after the MW change. What I believe is promising is the fact that here you can see even clearer how there's a change in the trend: average income decreases until the event and the stops. Why is this? Is it because higher income people start spending more time in local gyms, or is it because lower income people start going in better gyms located elsewhere?
Related to this, and related to my previous comment, I am therefore now computing the average _share_ of low income visitors to each POI: for each block group I compute the share of residents with an household income lower than 45K, and then I use that share to characterize visitors. 

I believe shares is the right way to go, as it will allow us to see what is driving that trend. I am refining the script so that it computes more than one demographic together, so @santiagohermo we will hopefully have share of college graduates soon. 


Lastly, here are the same specification run simply for the **total number of visitors**: 

**Parks**
![total_visits_712190_12_the_FEs_limit](https://user-images.githubusercontent.com/30894427/81945897-ab6aed80-95cc-11ea-9a1c-7bc2b1b4e670.png)
**Gyms**
![total_visits_713940_12_the_FEs_limit](https://user-images.githubusercontent.com/30894427/81945917-b32a9200-95cc-11ea-8c54-ee61d4385790.png)

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo Some updates guys! 

I haven't had the time (nor the clearest understanding tbh) on how to "update" this branch using #16 , so for the moment I simply reduced the event window consistent with what Diego did in #16. This ha brought interesting/promising developments: 

- To briefly recap, I built an zipcode-month level variable that captures the average median income of gym's (naics 713940) and parks' (712120) visitors, as well as the actual total number of visits in the two establishments. Even if still crude,  here are the event study plots I obtained when running the `test_event_study` scripts: 
**Gym Average Median Income**
![med_hhinc2016_713940_6_the_FEs_limit](https://user-images.githubusercontent.com/30894427/82560401-6819fd00-9b3f-11ea-9b44-5d344359c4ac.png)
**Gym Visits**
![total_visits_713940_6_the_FEs_limit](https://user-images.githubusercontent.com/30894427/82560417-71a36500-9b3f-11ea-9ce8-adfbf5385421.png)
**Parks Average median Income**
![med_hhinc2016_712190_6_the_FEs_limit](https://user-images.githubusercontent.com/30894427/82560441-7c5dfa00-9b3f-11ea-9dbe-0c6a74621617.png)
**Parks Visits**
![total_visits_712190_6_the_FEs_limit](https://user-images.githubusercontent.com/30894427/82560467-854ecb80-9b3f-11ea-8769-0c3147c8312c.png)

As you can see, the specifications with more controls do actually show something for Gyms, where the av. median income of visitors seem to increase after a MW change. For Parks there's a bit more of a trend. In terms of visits, we don't really see any clear effect. Note that all variables have been converted to log-scale. 

Starting from this, here are some considerations and possible next steps for this issue: 

1. In the current framework, the number of POIs for each zipcode has been fixed according to the procedure outlined in my previous comment (https://github.com/diegogentilepassaro/min_wage_rent/issues/27#issuecomment-628669338). As @santiagohermo suggested, I think it is important to also look at the actual number of establishments and how this changes in time. While it's true that oftentimes the opening and closing of a place is not something immediate that you can catch in a monthly panel, and different industries have different regulations to follow, waiting times etc, I think it's worth a try. 

2. SafeGraph released an updated version of the data back to Jan 2018. The downside is that there is 12 months less of data, and will hence force us to leverage only on MW changes that happened in 2018 and 2019 (I don't know, for example, if we would still have enough variation to distinguish calendar months from relative months). The upside however is that they significantly reduced the truncation problem in the data by upgrading the privacy protocols used to protect individuals. Specifically: 
    - _Old version_: POIs would appear in the monthly panel only if they received at least 5 monthly visits. _New version_: POIs appear in the monthly panel when they have at least 1 visit. 

    - _Old version_: For each POI, visitors home census block group was reported only if sending at least 5 visitors to the POI in a given month. This was causing some place to have less than 50 percent of visitors with known home location. _New version_: For each POI, visitors home census block group is reported only if sending more than 1 visitor. However, block groups sending between 2 and 4 visitors will all have 4 visitors reported. 

    - _Old version_: only customers were included in the data. _New version_: also workers are now included in the device tracked for each POI. This implies more work to separate the two, but also more precision in who is actually spending time in a given zipcode.

3. I kept thinking about how to best capture such an elusive concept as amenities and amenities' quality in a zipcode: we don't want to measure consumption (done already many times in relation with MW), so I think it's good to focus to understand WHO is actually spending time in a certain area of a city. Is it rich people? is it poorer people? Of course, this is intimately tied with consumption, but what is more interesting from our perspective is I guess to understand how an income shock to poorer people affects the housing market AND how this changes the _attractiveness_ of a place. But how can we define the attractiveness of a place? I think we are going in the right direction by proxying it with the _type_ of people that hang out there. But I think we should consider the following adjustments, in the light that different cities may have very different habits (e.g. Do rich people in Cali visit the same type of places of rich people in Minnesota? Can you afford the same lifestyle if you earn 100k in South Dakota vs in California? I don't think so)

   -  Assign each block group in a MSA or county to the percentile of the distribution of income, education etc. In this way each place will have a comparable relative scale SES characteristics. Compute then, for each POI,  the average percentile of visitors in a given month, and then aggregate to the zipcode level (either by average or directly aggregating at the zipcode level)

    - Alternatively/complementary: Regress the number of (log) visits on event study dummies for visits coming from different percentiles of the MSA (or county) distribution in terms of income, education, etc. This would show us, for each zipcode, how much the visits from lower percentile of THAT county distribution changed, and would allow us to compare it with the change in visits from other percentiles hence capturing how much the composition of visitors of certain zipcode changes. 


Sorry for the long post, any thoughts about that?

**Comment by gabrieleborg** [comment]
As per our meeting last week, let's pause on this task until we get 1) a draft; and 2) an initial model that will help us understand better which dimension of amenities we really want to capture.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg I will go ahead and close this issue and we can reopen a new one once we are ready to talk about amenities :D
