### ISSUE TITLE
Get ACS rents data

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#275]
It exists @diegogentilepassaro @gabrieleborg ! Very exciting.

I asked for Census help and I got this response

> Hi Santiago,
> Thank you for reaching out to the U.S. Census Bureau, and I apologize for the delayed response. 
> The best we can offer are the tables below. Lower is the 25th percentile and upper is the 75th percentile. I've also filtered to all ZCTAs in the U.S., hence why it says it's too big to display, but they can download. There will be ZCTAs without estimates, as I'm sure many hit the various filtering rules for display.

> 
 > [B25057: Lower Contract Rent ... - Census Bureau Tables](https://data.census.gov/table?q=B25057:%20Lower%20Contract%20Rent%20Quartile%20%28Dollars%29&g=010XX00US$8600000)
> [B25058: Median Contract ... - Census Bureau Tables](https://data.census.gov/table?q=B25058:%20Median%20Contract%20Rent%20%28Dollars%29&g=010XX00US$8600000)
> [B25059: Upper Contract Rent ... - Census Bureau Tables](https://data.census.gov/table?q=B25059:%20Upper%20Contract%20Rent%20Quartile%20%28Dollars%29&g=010XX00US$8600000)

> 
> 

> If you want to go the extra mile to get a mean, you would have to use table B25060 and B25056. You would divide the aggregate amount found in B25060 by the "Wish cash rent" estimate total. 

> 
> I hope this helps. Let me know if there is anything else I can do to help.
> Thanks,
> Ryan

I'll add the data to our repository in this issue. We need to discuss how to clean it up and add it to the pipeline.

**Comment by santiagohermo** [comment]
Data are available in [`GDrive/raw_data/acs_rents/`](https://drive.google.com/drive/u/0/folders/1R54Ap0Ea1tFwPt3ocnNb7nEGiAKj8bO3)

**Comment by gabrieleborg** [comment]
Hey guys! this is great! @santiagohermo let us know if you want to meet sometime to discuss what we need to do :)

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! I agree, time to discuss. I'll be in touch :)

**Comment by santiagohermo** [comment]
Can you help me explore these data @gabrieleborg? We need to go to the census website linked in the [opening comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/275#issue-2352298798) and explore whether we can find the variables I mention in https://github.com/diegogentilepassaro/min_wage_rent/issues/275#issuecomment-2191782612

**Comment by gabrieleborg** [comment]
hey @santiagohermo , sounds good - will work on it next week.

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro 

created scripts in [raw/ahs/code/build.py](https://github.com/diegogentilepassaro/min_wage_rent/blob/275-acs-rent-data/raw/ahs/code/build.py). 

Data are currently stored in `data/raw/ahs/output/acs_zcta_data.csv`. Shall we move it to GDrive?

**Comment by santiagohermo** [comment]
Per call:
- Rename the folder from `/ahs/` to `/acs_zcta/`
- Add rents variable in [this folder](https://drive.google.com/drive/u/0/folders/1R54Ap0Ea1tFwPt3ocnNb7nEGiAKj8bO3) in the code
- Make `/acs_zcta/` save output in `/drive/`, just like we did with QCEW

**Comment by gabrieleborg** [comment]
continues in #286
