### ISSUE TITLE
A simple model based on Kline and Moretti (2014)

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#30]
[BACKGROUND]
We want to write a simple model to theoretically understand what are the implications of a MW increase on rents and, specially, amenities.

[GOAL]
To write down a simple model and study the comparative statistics when a MW is introduced. The model will be based on [Kline and Moretti (2014)](https://www.annualreviews.org/doi/full/10.1146/annurev-economics-080213-041024) with a key modification: there will be two types of workers.

We will work on the model in [this](https://www.overleaf.com/project/5ec715e7356a3d00015f2065) Overleaf. We will bring it to the repo later if we decide it's worth keeping.

**Comment by diegogentilepassaro** [comment]
Update: @santiagohermo started writing the model [here](https://www.overleaf.com/project/5ec715e7356a3d00015f2065) and it's looking good! Whenever you give us the confirmation we can start independently solving it and see where that gets us!

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro ! 
It seems that an analytical solution would be hard to get (it may even be impossible) Thus, I've been playing with a solver of the model in Python. I am getting a weird result: It seems that something is forcing the number of high and low skill workers to be the same in both places. I will try to understand what is going on, and share it soon.

If you want to try some alternative way of solving it, go ahead! Something we could do is use the implicit function theorem to see how the equilibrium changes as we modify the low skill wage in one place.

**Comment by santiagohermo** [comment]
Update @diegogentilepassaro @gabrieleborg. I added to [the overleaf](https://www.overleaf.com/project/5ec715e7356a3d00015f2065) a section where I simulate the model. I created a branch where I store the [code](https://github.com/diegogentilepassaro/min_wage_rent/blob/41599fa057b00298a1f380c84425821a653a01f5/issue30-simple_model/solve_kline_moretti.py) to run the simulation (before I had a small mistake, @diegogentilepassaro. Now it works fine).

What remains to be done is to simulate the minimum wage changes. I will do this very soon.

If you guys want to give a try to the analytical approach, go ahead! It seems to me that the model doesn't have a closed-form solution, but I'm sure that partial derivatives can be characterized using the good old implicit function theorem.

**Comment by diegogentilepassaro** [comment]
Nice simulations @santiagohermo! I will do the math on Sunday :D

**Comment by gabrieleborg** [comment]
Great!! Same for me :)

**Comment by gabrieleborg** [comment]
@santiagohermo It seems I don't have the permission to access the Overleaf, could you check once you have the chance, please :) ?

**Comment by santiagohermo** [comment]
Do you have access @gabrieleborg ? If you are going to work on this, let me suggest starting with characterizing the equilibrium with minimum wage in section 4

**Comment by santiagohermo** [comment]
An extension that may be worth thinking about is allowing workers from one place to work in the other. [Perez Perez (2018)](https://jorgeperezperez.com/files/Jorge_Perez_JMP.pdf) finds that minimum wage changes on one side of the border affect commuting flows and employment shares, but do not affect residential shares. (See tables 2 and 3)

**Comment by santiagohermo** [comment]
(Reading for the field exam/prospectus) An interesting model of two cities with two skill groups is in the [online appendix](https://assets.aeaweb.org/asset-server/articles-attachments/aej/app/app/2011-0237_app.pdf) of [Moretti (2013) ](https://www.aeaweb.org/articles?id=10.1257/app.5.1.65)

**Comment by santiagohermo** [comment]
Per https://github.com/diegogentilepassaro/min_wage_rent/issues/39#issuecomment-652027065 we will postpone the discussion of the model. We will jump back to this in the future.
