### ISSUE TITLE
Add demographics data

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#31]
**Goal**

We want to add socio-demographic characteristics so to perform heterogeneity analysis over the MW impact on the housing market.

**Steps**

1.  Download SES data from 2010 census
2. Add SES data to main dataset

**Comment by gabrieleborg** [comment]
First pass of demographics @diegogentilepassaro  @santiagohermo!

I added demographics to the pipeline in a two-step procedure: 

1. I created `base/demographic` to host the code assembling the different tables from the census, and creating the demographic variables from the raw ones (e.g. the share of college graduates starting from the raw counts of residents with various educational attainments). The output is a simple USPS zip-code level csv file (see data manifest [here](https://github.com/diegogentilepassaro/min_wage_rent/tree/issue31-AddDemographics/base/demographics/output)). 

2. I added the demographics to the final, baseline datasets created with `derived/zipcode_month/code/create_final_panels.do`.  This is done fore the moment by simply setting a local switch to "yes": once the local is on, demographics are added to `drive/derived_large/output/baseline_rent_panel.dta` and  `drive/derived_large/output/baseline_listing_panel.dta` before saving them. I implemented it here as I didn't want to carry around this demographics too much in the dta building process since the data is already large enough. In this way we are adding info only to those zipcodes we end up using and we keep the data as light as possible.  If you believe we can implement it in other locations let me know! 

Right now this task should be basically over. I saw that @diegogentilepassaro opened #33 but he didn't mention heterogeneity analysis there. I will experiment a bit tomorrow, so let me know if you prefer to continue on this branch/issue or whether we shall do it on #33 !

**Comment by diegogentilepassaro** [comment]
Hola @gabrieleborg!

Quick question, are we going to use this issue to explore the heterogeneity by, for example, zipcode median income? Or should we move this to PR and do that in a new issue once everything is reviewed?

**Comment by gabrieleborg** [comment]
Hey guys! @diegogentilepassaro @santiagohermo 

I was about to answer that! In general I was thinking to PR this and open another task, but if you both want to do it here I have no problem :) 

As discussed I added a small piece of script in  [`derived/zipcode_month/code/addMinWage.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/issue31-AddDemographics/derived/zipcode_month/code/addMinWage.R) to create a column indicating, for each zipcode-month observation, which mw is actually binding. Whenever there are two equal min wage (e.g. federal and state are, say, 7.25) then I consider the smaller geography's mw as the one actually in place. In my example it would then be state. I then convert it to categorical variable for ease of interpretation in [`derived/zipcode_month/code/clean_gen_label.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/issue31-AddDemographics/derived/zipcode_month/code/clean_gen_label.do): I assign it increasing value as the geography gets smaller, i.e. 1 for federal, 2 for state, 3 for county and 4 for local. In this way we can see in the data manifest which is the prevalent one in different datasets: higher average means more county and local binding mw. 

As for the demographics, please refer to [my previous comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/31#issuecomment-640339798) for details on the implementation. 

as I anticipated at the beginning, I think we can PR this task, and leave the heterogeneity analysis in a specific/other issue.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! That sounds great. I agree in moving to PR and opening a new issue.

**Comment by gabrieleborg** [comment]
This thread continues in #36 .
