### ISSUE TITLE
Try event-study specifications using control units, experimenting with different FEs, and with first differenced models. 

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/min_wage_rent#33]
[GOAL]
Define one or two baseline specifications that we are confident about the econometrics.

[STEPS]
1. Experiment with different specifications that use different sets of fixed effects, for models with only treated units, and with both treated ad control. Use specifications only with the last event, and with all events. 
2. Try some specification in first differences.
3. Try clustering by county and by state.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg and @santiagohermo! This issue is done now, other than trying event-study specifications that all events, as that is waiting for #34. 

As we discussed in our meeting the FD specifications looks pretty good. The basic main regression model, which I called static, uses all treated and untreated zipcodes and is the following:

`\Delta ln Rents_zt = \gamma_t + \gamma_z + \Delta ln MW_zt + \epsilon_zt`

In the following table, column 1,  I present results from that model. In columns 2 to 4 I add linear, quadratic, and cubic zipcode-specific trends respectively.  Just to be conservative, the standard errors are clustered at the state level. 

![Screen Shot 2020-06-11 at 11 14 24 AM](https://user-images.githubusercontent.com/20582494/84396522-bf5a3d00-abd4-11ea-9b87-ca74ed9b0421.png)

Next, I extend the static FD model with leads and lags of `\Delta ln MW_zt` and I call that model dynamic. Results are below:

![Screen Shot 2020-06-11 at 11 16 47 AM](https://user-images.githubusercontent.com/20582494/84397474-15c77b80-abd5-11ea-9a9f-53bb86df8305.png)

As you can see, there doesn't seems to be a pretrend leading to the MW changes, and the effects are mostly on-impact and a period after. For reference I also constructed a table that computes the joint significance of the sum of the lags and the contemporaneous `\Delta ln MW_zt`, as that represents the total average treatment effect implied by the dynamic model. The results below:

![Screen Shot 2020-06-11 at 11 19 53 AM](https://user-images.githubusercontent.com/20582494/84397823-866e9800-abd5-11ea-8de4-99fffde77273.png)

**Comment by diegogentilepassaro** [comment]
Probably, it would be a good idea to construct a plot for the dynamic model that jointly shows the leads and lags dynamics and the sum, so that we can do with one nice figure. Alternatively, we could put the sum of coefficients as an extra row in the dynamic model table and only have one table. Or both.

**Comment by santiagohermo** [comment]
Nice work @diegogentilepassaro, thanks! I like the plot that you describe [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/33#issuecomment-642694393). We could do something like [Dube's QJE](https://doc-10-b4-apps-viewer.googleusercontent.com/viewer/secure/pdf/u4sfik30dohj8rujr5rfdtkpip4ogsdu/oiplkj2vb3j4cdvqoul4u9p7150vpr9j/1591886550000/drive/08983142586662316544/ACFrOgBZvNKNkT9OvPF9m9aFSYL4al-bkVcKLo3bWwskzx_XkvOytF5GSl4Pca6N9yGuXTiMPOFBn9oMXXVwezikVARiNQ8o0F64504p7Yda06A7RLXg3S1yZb5xmDDUibHxYdEtoC0hd-U4zVxM?print=true&nonce=p70eqr7e2gsh4&user=08983142586662316544&hash=60bl95bkuim2jhopf8bdul9o644erf4r) Figure 2, where they plot the coefficients of the event studies for each bin plus a _cumulative sum_ of them.

**Comment by diegogentilepassaro** [comment]
As for the event study, in our specification using only one event per zipcode (the latest event), I have tried different things. First, [Jaravel and Borusyiak (2016)](https://scholar.harvard.edu/xavier/publications/revisiting-event-study-designs) point out that in a case with only one event per unit two-way fixed effects event-study models are not identified as we cannot really disentangle within a unit what variation corresponds to time passing by and what corresponds to time relative to the event. 

However, in our case, the units are zipcodes, so changing the zipcode FEs for county FEs is well identified, as within a county, there are zipcodes treated in different times for quite some counties. Although not ideal I gave that a try.  When we compare the results we get when using zipcode FEs (and zipcode-specific quadratic trend) and county FEs (with county-specific quadratic trend), it looks like the county FEs do much better. 

**rentpersqft - Zipcode FEs and zipcode-specific quadratic trend**
![Screen Shot 2020-06-11 at 11 53 13 AM](https://user-images.githubusercontent.com/20582494/84401919-380fc800-abda-11ea-8b51-37188e21cd8c.png)

**rentpersqft - County FEs and county-specific quadratic trend**

![Screen Shot 2020-06-11 at 11 54 58 AM](https://user-images.githubusercontent.com/20582494/84402070-6392b280-abda-11ea-8576-b56f43dae15c.png)

For the listing the picture is similar. 

The next exercise was to use both treated and untreated units in the event-study. I used as a baseline specification, the one with county FEs and county-specific quadratic trends. For adding a control group I generated a variable, which I called treated, equal to 1 if the relative event var is non-missing and zero otherwise. Then, I set the missing values of the relative event var to some constant. Finally, I ran the event-study model controlling for a dummy for whether you are treated or not using all (treated and untreated observations). Note that there is also an extra estimate in the relative event var that corresponds to the relative event category of untreated units. 

The result is below.

**rentpersqft - County FEs and county-specific quadratic trend with control units**

![Screen Shot 2020-06-11 at 12 00 15 PM](https://user-images.githubusercontent.com/20582494/84402685-25e25980-abdb-11ea-9051-237b3e10bcdd.png)

My hunch now is that we should prioritize the FD models for now, but start adding to this current experiments the use of more events per zipcode once #34 is added to master. One last comment, is that we really need to increase our sample sizes! For that we should (i) map the USPS zipcodes that don't map to ZCTA manually, we should (ii) explore using zillow zipcodes starting in mid 2015 instead of January or even 2016 so that we have more than now, and we should (iii) check if the zillow data by county has more coverage than the zipcode data (my guess is that it should) so taht we can complement our analysis.

**Comment by diegogentilepassaro** [comment]
@santiagohermo could you please make sure that you agree with my comments? Let me know if you have any comments or suggestions and after that I will send this issue to PR so that you can take a deep look and we can take to master what we think fit.

**Comment by diegogentilepassaro** [comment]
@santiagohermo I like the idea of constructing a figure like [Dube's QJE](https://academic.oup.com/qje/article/134/3/1405/5484905) figure 2. Maybe we can do that now or while in PR. What do you think?

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro. Nice exploration! I made a quick pass on [your comments](https://github.com/diegogentilepassaro/min_wage_rent/issues/33#issuecomment-642719481) and they make sense to me (I haven't read jaravel yet, I'll get into it soon). Although those event study plots are not quite sharp as the old ones, they still look quite good.

I think we are good to move to PR and I will make a deeper pass on the code. We can discuss implementing the figure there.

**Comment by santiagohermo** [comment]
Thread continues in PR #35
