### ISSUE TITLE
Research plan after initial draft + Feedback

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#39]
**[BACKGROUND]**
We are close to finishing an initial draft in #37. After closing it, we  want start working on an improved version of the research project that includes all the feedback we've received so far

**[GOAL]**
The goal of this issue is to collect the feedback received so far and settle on an action plan going forward.

**Comment by santiagohermo** [comment]
I opened up this issue to start collecting feedback and discuss what to do after the draft is done@diegogentilepassaro @gabrieleborg. I wanted a place to comment on our meeting with Jesse today, but I think it is useful to collect everything in one place.

Summary of meeting of @diegogentilepassaro and  @santiagohermo with Jesse Shapiro on 6/30.
1. To do this project correctly we need to deeply understand how the Zillow data is constructed and what it represents. For example, if we capture a small share of rentals then we would worry a lot about compositional changes around MW events.
    - To complete this it is crucial to connect with Zillow. We plan to send them the initial draft once it's done, and discuss data construction. It would also be useful to get access to their microdata.
   - While useful, Jesse gave less importance to comparing Zillow to alternative rents data.
2. The final version of the paper needs a model, as many possible channels are possible in this setting. However, we shouldn't invest too much time on it for now. We should make sure we have established reliable facts first.
3. Benchmarking the size of the effect. One useful way to start is looking at the elasticity of housing to labor demand in Diamond (2016) and building from there.

**Comment by santiagohermo** [comment]
Tasks after meeting on August 25th (fyi @diegogentilepassaro @gabrieleborg)

1. Finish up data
    - Contact Zillow: To better understand data and ask for more data
    - Consider some alternative to Zillow (Trulia is also Zillow)

2. Improve first differences specification
   - Read literature
   - Try alternative models

3. Benchmark magnitude of effects

4. Model

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro 

Some updates: 
1. Finish up data: 

-  We contacted Zillow asking for: a) clarifications on the data we are using; b) additional data. Waiting for a reply

-  I looked for alternative data. Unfortunately there's no much around at the zipcode level. We could try to contact Zillow competitors, but being Zillow the largest website, we will surely get smaller samples.

2. First Diff spec: 
- Diego is trying alternative models, mostly starting from [Meer and West](http://jhr.uwpress.org/content/51/2/500.abstract). 

- Using the first-difference model, I am assessing the presence and relevance of heterogeneous effects. For more info see #40 

3. Benchmark magnitude
This would likely follow the first-difference assessment by @diegogentilepassaro  and #40  

4. Model

**Comment by santiagohermo** [comment]
### Comments breakfast September 23
Presentation by @gabrieleborg. Slides: 
[Breakfast_Sep2020.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5268030/Breakfast_Sep2020.pdf)

- [Jesse Bruhn, JH] Motivation is that MW aims at lower inequality but may increase it because some of that money ends up in landlords?
- [Santi Hermo, SH] What is the meaning of ''strong balanced panel'' exactly? I think we have some missing observations in between months.
- [JB] What is issue that makes end up with so few zipcodes? Gabri: with zipcode we get 11% of zipcodes, and trying to balance the panel we end up with 3%. JB: use zipcodes and control for year of panel entry FE interacted with time. Try to keep more zipcodes
- [John Friedman, JF]: Understand the composition of your rental variable within zipcodes, since it may be correlated with MW changes. Need to know more information about that. Diego Gentile, DGP: we compare the time series with other rental sources
- [JB] One to one mapping between distributed lag and event study? Will share paper about this
- [JF] Using zipcodes may lower precision, but does not add any variation that leads to identification. Why? Smallest variation comes from cities. Be precise with the identifying assumption
- [Julia Tanndal, JT and JF] Using zipcodes can be helpful for studying heterogeneity
- [JB] The effects come about very quick. Probably because you only see new apartments. Can you map this pattern back to the full structure of leases? (the ones that are in place when there is a mw change don't change) Try to rationalize it
- [JF] Why are the s.e. so much larger in t = 0 compared to t = 1? A little bit weird the pattern of s.e. changes
- [JF] Consider LODES dataset to identify where people live and work
- [JS] Reweigh to target measures of metro areas. Matching rural seems unlikely given non-random selection of the zipcode panel
- [JS] How do the results vary depending on the elasticity of housing supply across cities?

**Comment by santiagohermo** [comment]
Per meeting @diegogentilepassaro @gabrieleborg 

- We are going to focus on wraping up open issues:
   - Finish #43 and #46. @gabrieleborg is going to wrap up #43 and #46 and send them to PR, then we open a follow-up to combine them
   - After that, complete the heterogeneity #40 (consider using the simple diff-in-diff)
   - Finish up #47

- Later, we would like to:
   - Control for economic shocks (consider using CPS at the msa-month level)
   - Control for changing composition of houses available for rent (consider using information of listings)
   - Consider heterogeneity based on the elasticity of supply at the zipcode level (consider using land availability at the zipcode level as proxy)

**Comment by gabrieleborg** [comment]
Morning @diegogentilepassaro  @santiagohermo, 

while you review the PRs, I'll go on and start working on controlling for economic shocks. I have assigned myself for the moment, but we can discuss later on if someone wants to join.

**Comment by santiagohermo** [comment]
Comments for the new draft (October 2020), going until section 3: [annotated_SH-The_Impact_of_MW_changes_on_Rent___2020_10.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5393841/annotated_SH-The_Impact_of_MW_changes_on_Rent___2020_10.pdf)

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo 

Thanks again for your help with the draft. 

I have already posted a couple of more detailed post on the improvement I have adopted in #55 and #40. Here I wanted to recap in a more general way what we need to do now: 

1. take stock of comments (shall we send the draft to someone else)? 
2. PR #55 and (maybe #40)
3. Theory / general mechanism: how can we make our results more compelling ? is there any welfare-related exercise we can add? 
4. Test for compositional bias using variation in number of listing ? (this is more of an experiment, but John's hinted at it)
5. Think a bit more about non-parametric controls for local shocks (Diego is the one that have thought about this the most).

**Comment by diegogentilepassaro** [comment]
@gabrieleborg thanks for posting the plan! It sounds great to me and I am happy to discuss more on Thursday.

1. I would add the benchmarking exercise and some discussion and then circulate it with Jesse, Neil, Ken, Matt Turner, and with Matt Pecenco. Ideally we send it to them through an email that also asks for a Zoom metting soon. What do you think? 
2. I am happy to PR #55, and then move to #40. I will post my comments directly there once I am through. Will start tomorrow or on thursday. 
3. Benchmarking should be a start here. ONce we have that written and we get comments from the professors, we can move on and keep improving.
4. Not sure what we gain as compared to controlling for the permits, but I am happy to discuss and give it a try!
5. This is a good idea. We can do this on an issue that also explores comparing zipcodes within states!

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg @diegogentilepassaro! I agree with your outline. A few comments:

- As Diego reviews #55, I can start with adding the benchmarking exercise to the draft. I'll open up an issue for this.

- I agree with circulating a draft! I mentioned the draft briefly to Jesse yesterday in a meeting. He said he'd be happy to take a look! Of course, he insisted asking whether we understand the data better. I said we tried to contact Zillow and got no answer, so he suggested  trying to go through [CareerLab](https://www.google.com/search?q=careerlab&rlz=1C1SQJL_esAR784AR784&oq=CareerLab&aqs=chrome.0.0i355i457j46i175i199j0l2j0i10l2j46i10i175i199j5i44.2410j0j7&sourceid=chrome&ie=UTF-8), or searching and contacting someone with a PhD in Zillow (who may be more sympathetic with our cause)

- I agree that it would be nice to address the threat of compositional changes in listings. However, I think that we already have a lot of robustness, so it would probably be better to tackle this in parallel with further improvements in model/welfare/interpretation.

**Comment by santiagohermo** [comment]
Comments following meeting with Jesse, November 2nd 2020. (@diegogentilepassaro @gabrieleborg)

- _Pre-trends and anticipatory effects_. Can't test both confounders and anticipatory effects with pre-trends only. Need to make assumptions on any of those. Be clear about what assumptions you are making!
    - Idea: run model on some dates where MWs are announced?
- _Bad control_: 
   - Use for example avg.wage for sector that have very little minimum wage workers.
   - Building permits. If assuming housing supply fixed, can't use that control! Or can use permits that are unlikely not affected by MW changes.
   - Can use them as sensitivity analysis. Don't use it as main argument in introduction,
- _Estimating after aggregating your data_: sounds like a good idea to do this to compare to Yamagishi and Tideman. 
- _Linear and quadratic trends_. 
   - Is there any model under which these are true?
   - Good for sensitivity though
   - Focus on proxying for main confounder: State of the economy
- _Model_. First objective: draft with clear story for identifying assumptions. Model could be useful as well, but no main focus.
- Come up with nice benchmarks for the magnitude.
- _Experienced minimum wage_. Small weights don't sound like a big deal. In any case, approach by thinking of taking top 90% destinations or something would be a reasonable alternative.

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg:

Making a note here so we remember to think about and answer comments from Matt Turner.

**Comment by santiagohermo** [comment]
Meeting today (fyi @diegogentilepassaro @gabrieleborg):

On [the feedback](https://github.com/diegogentilepassaro/min_wage_rent/issues/39#issuecomment-720578468):
  - A story for the confounds. Two main threats: economic shocks and housing supply responses. We think the second is fixed due to a short window (use building permits to show this). We control for economic shocks (make sure they are not "bad controls")
  - Why do you see effects on the event, and not earlier? Mechanism of supply and demand within the period, the effect shows up when the demand increases.
  - Ditch polynomial trends from main specification. 
  - **PRACTICAL IMPLICATIONS**:
    - Fix static table with following controls: col 1 no controls, col 2, 3, 4 wages establishment-count employment, col 5 all controls. Add polynomial trends in appendix (zipcode-specific, and think about state-specific trends)
    - show dynamic model and discuss pre-trends using economic controls. Illustrate better the cumulative sum. How? Panel A only coefficients, Panel B cumulative sum
    - Reorganize tables and re-write paper (be clearer in assumptions)

- To Appendix:
   - Tables with all coefficients
   - Estimating after aggregating data // use zipcode at county and state levels // think about average of medians

- Model. Move to appendix and use for benchmarking. Come up with alternative benchmarking.

**Comment by santiagohermo** [comment]
Some ideas I wrote from today's meeting @diegogentilepassaro @gabrieleborg 

- Construct a test to argue that first differences is more efficient, and argue from there why you'll use it

- Run first-difference models with zipcode-level data using county and zipcode FE. May be useful for arguing in favor of identification

- Bring in zillow data at the county and state and run main models. May be useful for arguing in favor of identification

- Think of pooling all zillow variables using "quality" in the specification. Idea for January

- Maps. 
   - Keep two maps of the whole US: sample in the top, urban population density in the bottom.
   - Zoomed-in maps. Think how to introduce them. It depends on how we introduce the experienced MW

- Experienced MW. Incorporate as an extra step in the identification. Don't apply as main argument for now.

**Comment by santiagohermo** [comment]
We have completed a second draft in #65 (see this [summary comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/65#issuecomment-745434534)). We will be getting a round of feedback based on this draft, and organize to continue working next year. 

Both this issue and that [summary comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/65#issuecomment-745434534) contain some ideas of things we may want to implement.

I will close this issue @diegogentilepassaro @gabrieleborg
