### ISSUE TITLE
Heterogeneity & Salience

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#40]
**Overview**
John's comment : _"If these results are correct, then I think you also need to do a bit of broader thinking on how exactly these effects can be so big.  For instance you need to think about the fraction of income that people spend on rent, do more on how the effects vary across the income distribution, and think about why the incidence would appear in this way."_

**Goal**
To better study the presence of heterogeneous effects of MW changes on zip codes. We want to understand whether different zip codes present different _transmission_ rate from MW to rent (e.g. whiter, less-educated, poorer, etc). A focus shall be put on differences in income as this determines, along with the average rent, the share of income spent on rent. 

**Steps**
- Read literature on heterogenous effects in panel data and event studies. 

- identify suitable demographic characteristics to represent zip codes. 

- test specification. 

**Note**
[This](https://economics.ucsc.edu/research/downloads/JOLE_ChatterjiChayFairlie_TheImpactofSetAsides_March18th2013.pdf) paper by Ken Chay and coauthors show a way to define heterogeneous effect in panel data sets.

**Comment by gabrieleborg** [comment]
Hey @santiagohermo @diegogentilepassaro ! 

I started working on heterogeneity of the MW effect on rents. As discussed, I started working on our preferred specification, the first difference one. I explored how the effect varies across different dimensions characterizing zip codes, and I implemented 2 different approaches. 

**Demographics Variables**
Besides the demographics we already had (now correctly computed after I reviewed [base/demogrpahics/code/make_demograhics_ziplevel.R](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/base/demographics/code/make_demographics_ziplevel.R)), I also computed the rent to income ratio. I believe this is going to be an important feature to look at, as it will inform us on the salience of such effect identifying those zip codes where residents pay a lot for every dollar they earn. To do that I had to combine a "fix" characteristics (as recorded in the 2010 census), income, and a time-varying one, rent. To do that I selected one month in our panel and looked at the cross-sectional distribution. Specifically, I selected January 2014 because it's the first month where we have at least 90 percent of non-missing rent observations in our final baseline rent panel. I then divided annual income by 12 and divided the monthly rent for the "monthly" income. Here is the distribution of the ratio I obtained: 
![image](https://user-images.githubusercontent.com/30894427/92792817-df3c0100-f37b-11ea-9776-b1ff29181851.png)
One important thing to keep in mind is that such measure negatively correlates with annual income: the higher a zip code income, the lower the ratio as people appears to spend less on rent (is it because there are simply less rental units and more home owners, or because rents are lower in relative terms? that we don't know at the moment): 
![image](https://user-images.githubusercontent.com/30894427/92793201-3346e580-f37c-11ea-8444-d393d53300a9.png)
For each demographics, I then assigned zip codes to quartiles of the distribution. We initially used quintiles, but I decided to reduce the number to 4 so to have more sample size in each group. The Last important thing to mention is that by computing such quartiles just before analysis (specifically in [analysis/first_differences/code/preclean.do](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/analysis/first_differences/code/preclean.do) we are de-facto computing quartiles of the final sample, not on the entire US zip codes. To do that we would need to compute such statistics in `base`. I am still not sure what makes more sense, so we should talk about it. 

**Heterogeneity by groups**
The first type of analysis I have been doing is a simple heterogeneity analysis by group, where I run a given specification separately for each quartile of a given characteristics. Here I assume that all assumptions previously tested remain valid, and I therefore use the distributed lag model with leads only. I do this following Dube et al. (2019) and their heterogeneity analysis. I then compute the cumulative effect in the 6 periods under analysis (event period and the 5 months after) by combining the estimated coefficients with the Stata `lincomest` command. This should give me the total percentage change in rents caused by a 1 percent change in MW. I still haven't come up with a script to put everything together so for the moment let me paste here some Stata output: 

*Rent-Income Ratio*
![Screen Shot 2020-09-10 at 4 01 10 PM](https://user-images.githubusercontent.com/30894427/92796051-de589e80-f37e-11ea-8efa-0493bb65ec05.png)

*Median Income (state quartiles)*
![Screen Shot 2020-09-10 at 4 18 12 PM](https://user-images.githubusercontent.com/30894427/92798774-3c868100-f381-11ea-9e29-18535ab15eae.png)

*Share of College Graduates (state quartiles)*
![Screen Shot 2020-09-10 at 4 19 24 PM](https://user-images.githubusercontent.com/30894427/92798943-663fa800-f381-11ea-823c-d86769607b3e.png)

*Share of Blacks (state quartiles)*
![Screen Shot 2020-09-10 at 4 20 24 PM](https://user-images.githubusercontent.com/30894427/92799115-8a9b8480-f381-11ea-86d2-9f81ad0af4f3.png)

*Share of houses rented (state quartiles)*
![Screen Shot 2020-09-10 at 4 24 22 PM](https://user-images.githubusercontent.com/30894427/92799801-17464280-f382-11ea-9ca2-0a55675da577.png)

*Share of Low Income Households (<40K/year) (state quartiles)*
![Screen Shot 2020-09-10 at 4 24 00 PM](https://user-images.githubusercontent.com/30894427/92799738-0990bd00-f382-11ea-9329-63a5fa85cd8c.png)

*Unemployment Share (state quartiles)*
![Screen Shot 2020-09-10 at 4 25 03 PM](https://user-images.githubusercontent.com/30894427/92799908-304ef380-f382-11ea-9e68-8c8e54b7b996.png)

As you can see not many of the cumulative coefficients are significantly different from zero. I am still trying to interpret this, so please let me know what you think. The significant coefficients seem kind of contradictory: on one hand we have a large increase in zip codes with lower rent-to-income ratio, hence richer zip codes on average. On the other hand however we have larger and significant effects in the 1st quartile of the education distribution and in the 4th quartile of the black and unemployment distributions, all characteristics we know to be associated with lower incomes. 

On this side, I think that we need to discuss whether: 

- it makes sense to look at the cumulative effect. Maybe it's just better to keep the results from the static model as we briefly presented in the draft. 
- to which degree are these estimates reliable. As previously mentioned, I intentionally used the model with no lags following Dube et al. If I instead switch to a full distributed lag model, almost all series show pre-trends. In this sense, I don't think however this is the right thing to do, as MW policies are applied uniformly to all zip codes in a given area. 

**Relative Heterogeneity with interaction terms**
 As a second approach, I adapt the event study specification in Chatterly, Chay where I add, in a separate model for each demographic, interactions between lags and lead and the categorical quartile variable. I select the 1st quartile as baseline category, so that the estimated coefficients capture the difference with respect to this category: 

*rent-to-income ratio*
![image](https://user-images.githubusercontent.com/30894427/92804122-10b9ca00-f386-11ea-90ad-db605b94b690.png)

As you can see, this is very difficult to interpret. The main idea is that higher quartiles show  a similar change in rents following a MW change in the same month, but then they show a 5 percent lower change in month t+2. Such difference closes after that. Reassuringly we don't have much differential pre-trends, but again, I believe this is very diffcult to interpret as we are in a first difference model.

**Comment by gabrieleborg** [comment]
As per our discussion on Sep, 10th I will look for ways to measure the share of MW workers living in a zip code (and potentially the share of MW workers that are renters).

**Comment by gabrieleborg** [comment]
Morning guys! @santiagohermo @diegogentilepassaro 

I worked on coming up with a measure for MW workers. It took me a while to pin down exactly how to do it. First I looked over data sources that could give us time variation as well, but without access to individual level data there's no easy solution. I therefore come up with a census-based time-invariant measure that shall proxy for MW workers (and renters) and give us at least a zip codes cross-sectional differentiation. The procedure to build this comes in 2 steps: 

1. In [base/demographics/tract_avgMW1318.R](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/base/demographics/code/tract_avgMW_13_18.R) I compute, for every census tract, the average MW between the year 2013-2018. With this I then calculate what would be the annual income for a) a single earner MW household; b) a 2 MW earners household. I choose the period 2013-2018 because I will then use this variables together with income information from the 2014-2019 ACS, where they specify how income refers to the previous year (hence 2013-2018). 
2. In [base/demographics/make_MWrenters_ziplevel.R](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/base/demographics/code/make_MWrenters_zipelevel.R) I then merge MW data in and calculate the number of households for each tract whose annual income fell approximately below the MW level. I say approximately because the count is based on income bins. The annual MW income almost always fall within a bin, so I assign that bin to be MW households only if the annual MW income is higher than its mid-point  (if, for example, we have an annual MW income of USD32000, I assign all bins up to 25k-30K to be MW households, while the 30K-35K not). The big problem here is that there are no info for each single bin about how many households are single vs 2-person earners. I hence apply to solutions:
    - I assume that all households are either single or double earners, and compute 2 distinct numbers of MW workers. 
    - I assume a uniform distribution of single vs double earners across bins. This allows me then to use the general info about 
    single vs double earners present in the ACS to compute a weighted average for each bin, where the number of 1 person MW households is weighted by the share of 1 worker households in that tract, and the same goes for 2 person households. 

Of course, these measures are not perfect, and I created different versions of them using slightly different data from ACS, but at least it allowed us to use the info on income of renters (available in rather large bins though) to compute an approximation of how many MW workers there are that are renters as well. The final step is to crosswalk all these numbers to zipcode. 

I then add such metrics to [base/demographics/make_demograhics_ziplevel.R](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/base/demographics/code/make_demographics_ziplevel.R), along with the more classic ones, so that they are present in the final panels once we run `derived`. 

I then assembled the heterogeneity table I showed you last night on Whatsapp. Unfortunately there's no easy way to put all those estimates together automatically, so in [analysis/first_difference/output](https://github.com/diegogentilepassaro/min_wage_rent/tree/Issue40-Het-and-Salience/analysis/first_differences/output) you can find the individual tables for each demographic. I added the table to the draft. Here's a pic of it: 
<img width="515" alt="Screen Shot 2020-09-15 at 8 53 10 AM" src="https://user-images.githubusercontent.com/30894427/93212884-3140a600-f731-11ea-8251-814905c61fae.png">

Thankfully, you can see that the effect is increasing in the quartiles of MW workers present in zip codes. The effect in the 4th quartile is statistically significant at 10% level. In the last row you can see a similar picture when I use the share of MW workers that are renters, which is very good. However this last measure is still based on the 2 workers assumption. I am updating the code now to get the "weighted average" version of that one too. 

Let me know if all this makes sense to you guys! I am also currently trying an alternative specification that doesn't require to split the sample across quartiles, so if that works we would gain in precision. Finger crossed!

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! I made a quick read from your comment and overall I think it makes sense. The results seem good too (nice table!), although it is weird how the first quartile of the share of MW rents is larger than the two middle ones.

Question: do you think it's possible with your computations to get some approximate estimate for the parameters I call in the [benchmarking exercise](https://github.com/diegogentilepassaro/min_wage_rent/blob/7cf8323041e40bd076ce407428626bb483343dc9/issue44-benchmark/benchmark.pdf) `\underline{s}` and `\overline{s}`?

Looking forward to our meeting!

**Comment by gabrieleborg** [comment]
@santiagohermo yes we can try to use those indeed! Even though imprecise they might help us. A clarification: with share of housing, you mean share of total housing, or share of rental housing only?

**Comment by diegogentilepassaro** [comment]
Nice table @gabrieleborg! One other question: what is the legend for the significance symbols?

We can discuss soon!

**Comment by gabrieleborg** [comment]
@diegogentilepassaro I forgot to add it! the symbols are: + .10, * .05, ** .01, ***.001

**Comment by diegogentilepassaro** [comment]
That would be great! :D

**Comment by diegogentilepassaro** [comment]
@gabrieleborg one question about step 1. in [this comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/40#issuecomment-692698039): Is it possible to compute the average MW between the years 2013-2018 for each state or even better for each zipcode?

**Comment by gabrieleborg** [comment]
@diegogentilepassaro yes, but I am not sure for what you would use it? I do it tract level because the census variables are tract-level to begin with. In order to compute the number of households below the MW earning threshold you need a tract-level variable. Once I obtain all counts, i then crosswalk everything to zip code. 

Alternatively you could first count all households in each zipcode with the crosswalk, and then compare them with the zipcode level minimum wage but this implies two separate crosswalks procedure (one for the MW thresholds and one for all demographics), and this I sense it will make lose precision. What do you think?

**Comment by diegogentilepassaro** [comment]
I am just worried that the average MW is a weird measure if we compute for the whole US because, for example, earning $10 an hour in San Francisco is very different than making that in Atlanta. We should compute the share of MW earners on each zipcode based on the MW that prevails there if possible or at least as close as possible to that. Does that make sense?

**Comment by gabrieleborg** [comment]
Yes but that's what I am doing! maybe I expressed myself wrong, but that's exactly what I am doing :)

**Comment by gabrieleborg** [comment]
each unit has its own threshold

**Comment by diegogentilepassaro** [comment]
Ahh thats great then @gabrieleborg! Thanks for clarifying :D

**Comment by gabrieleborg** [comment]
Hey guys @diegogentilepassaro @santiagohermo, 

As discussed in our call on Thursday, Oct 1st 2020 I will work with LODES data to characterize zip codes according to the characteristics of the residents' (i.e. characteristics of workers that _live_ in zipcode X), and of workforce (i.e. the characteristics of the workers that _work_ in zipcode X). Specifically, I will start computing for each zipcode X: 

1. Share of residents with MW characteristics (i.e. low-income and younger). This is a bit redundant since we already tested these features using census data, but here I can refine the characterization since I can look at the joint distribution, and identify, say, low income workers among younger people. 
2. Share of workers with MW characteristics. 
3. Share of residents that work in a different: a)zipcode; b)city; c) county; d)state
4. Share of workers that live in a different: a)zipcode; b)city; c) county; d)state

Points 3 and 4 will take a while I expect, so feel free to jump in this discussion so we can better tune the construction of those variables as I go!

**Comment by gabrieleborg** [comment]
First update using LODES data @santiagohermo @diegogentilepassaro: 

Before explaining what I did, I thought a bit more about points 3) and 4) from my previous post and I don't think it makes sense to build them. At least in the way I first planned to. I will explain this tomorrow in our meeting. 

First, in [`base/lodes/code/make_lodes_ziplevel.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/base/lodes/code/make_lodes_ziplevel.R) I build a ziplevel data set with workers-related variables computed from LODES data. In order to create shares of residents and workers I don't need to use the origin-destination matrix, but only the _resident area characteristics_ and _workplace area characteristics_ data. At this stage I decided to create an "excess of possible measures" so to have them all ready to be selected if needed. At the end of the script I filter the one I started using. The multiple combinations of dataset types and segments made the variable naming process a bit cumbersome. I have adopted this rule: [POV][SEG][TYPE]_vardescription, where [POV] stands for Point of View (h for "home", and w for "work"), [SEG] for Segment, and [TYPE] for Type. An example of variable name hence is: halall_njob_29young: [h]ome - [al]l segments - [all] types - no. jobs for workers 29 yrs and younger, measuring the number of workers from all segment and all types that resides in a given zipcode.  You can find the list of all acronyms in the code. 

In the end, I focused on all jobs and outputted the only following variables:

- share of young workers (29 or younger) living in a zip code, out of total workers (both zipcode and state share)
- share of young workers working in a zip code, out of total workers (both zipcode and state share)
- share of young workers living in a zip code, out of low-income (<$1250/mo) workers (both zipcode and state share)
- share of young workers working in a zip code, out of low-income workers (both zipcode and state share)
- share of young _and_ low-income workers living in a zip code, out of total workers (both zipcode and state share)
- share of young _and_ low-income workers working in a zip code, out of total workers (both zipcode and state share)

I then modified [`derived/zipcode_month/code/create_final_panels.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/derived/zipcode_month/code/create_final_panels.do) to include such variables into the final baseline rent panel. In [`analysis/first_differences_wgt/code/preclean.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/analysis/first_differences_wgt/code/preclean.do) I then compute the quartiles for such variables and finally use the quartiles to run the static model for heterogeneous effect in [`analysis/first_differences_wgt/code/first_differences.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/analysis/first_differences_wgt/code/first_differences.do)(I only used state shares at the moment): 

**share of young _and_ low-income workers living in a zip code, out of total workers:**
<img width="924" alt="fd_static_heter_halall_29y_lowinc_ssh" src="https://user-images.githubusercontent.com/30894427/95390057-c3684400-08c2-11eb-94a3-7c78ba12dc5a.png">

**share of young workers (29 or younger) living in a zip code, out of total workers:**
<img width="924" alt="fd_static_heter_halall_njob_29young_ssh" src="https://user-images.githubusercontent.com/30894427/95390148-ebf03e00-08c2-11eb-858c-4e40782da4e4.png">

**share of young _and_ low-income workers working in a zip code, out of total workers:**
<img width="924" alt="fd_static_heter_walall_29y_lowinc_ssh" src="https://user-images.githubusercontent.com/30894427/95390183-01656800-08c3-11eb-9e7a-783fafdc9054.png">

**share of young workers working in a zip code, out of total workers:**
<img width="924" alt="fd_static_heter_walall_njob_29young_ssh" src="https://user-images.githubusercontent.com/30894427/95390247-1641fb80-08c3-11eb-9eaf-daa51ff8a96d.png">

**share of young workers working in a zip code, out of low-income workers:**
<img width="924" alt="fd_static_heter_welall_njob_29young_ssh" src="https://user-images.githubusercontent.com/30894427/95390436-66b95900-08c3-11eb-9890-062349476982.png">


What emerges is that we have an heterogeneous impact where MW workers (proxied by young, low-income workers) **live**, as opposed to where they work. Indeed, you spot a similar pattern when you focus only on young workers. This is interesting because it confirms what census demographics were pointing at, namely that there's an hidden cost of MW policies disproportionately bear by younger, lower income people.  

I am currently trying to understand why the 4th quartiles of the workplace-based variables have such a large SE. Intuitively, those are the zipcodes with the highest concentration of young workers. I think it's reasonable to expect that these are rather industrial/rural places with probably fewer Zillow rentals, and consequently higher variance in our dependent variable.

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro @santiagohermo, 

When creating heterogeneity results for the draft I have also updated this branch for sake's of clarity. Specifically, I have update it first from master, and then worked on the [`analysis/first_differences/code/estimate_heterogeneity.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/analysis/first_differences/code/estimate_heterogeneity.do). Now the script produces both plots and the table that we are using in the draft. 

I think we may want to PR this after #55, that contains more prominent changes.

**Comment by gabrieleborg** [comment]
Thread continues in #62
