### ISSUE TITLE
Basic benchmarking of effects

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#44]
[GOAL]
The goal of this issue is to come up with a simple computation to benchmark the effect of the MW on rents that we are finding now.

[STEPS]
1. Come up with a simple framework to express our object of interest, d ln r/d ln MW, in terms of parameters (share of MW earners in zipcode, share of income spent in earnings by MW earners, etc)
2. Come up with numbers for those parameters and figure out what effect they imply
3. Compare with our estimates of the effect

**Comment by santiagohermo** [comment]
Hey @diegogentilepassaro @gabrieleborg, I had an idea for step 1 as we talked today which I just implemented! (I had to do it now or I would have lost it!)

Specifically, I assumed a very simple equilibrium in a zipcode housing market and derived an expression for our object of interest in terms of

- the elasticity of housing demand to the minimum wage and to rents for MW households
- the elasticity of housing demand to rents for non-MW households
- the elasticity of housing supply
- the minimum wage to rent ratio
- the share of housing occupied by MW earners
- the share of housing occupied by non-MW earners

I compiled my reasoning in [this pdf](https://github.com/diegogentilepassaro/min_wage_rent/blob/2e3274445b16efb60f9f8954a237cf44188b830b/issue44-benchmark/benchmark.pdf). Let me know your thoughts and whether you think it makes sense! Once you are onboard, we can move on to plugging in some numbers and getting our benchmarks

**Comment by gabrieleborg** [comment]
That's very cool @santiagohermo ! 

I think this is a great start. My comments below: 

1. Can you show me how you obtain (1) though? I couldn't reproduce your results, as I am not sure how to fully differentiate with respect to 2 variables. 

2. Regarding equation (2), we can get shares and MW/rent ratio directly from the data (hopefully), but how would you compute the elasticities we need to benchmark our estimate ?

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! Quick answers:

1. I'll add the derivation as soon as I have some time (I have it in my notebook here). Then we can check whether I screwed up or not haha
2. Those elasticites are the hard part, yeah! I would take the value from some paper, e.g., Diamond (2016). We can also just plug in made-up numbers that we think make sense

**Comment by santiagohermo** [comment]
Update: new pdf [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/7cf8323041e40bd076ce407428626bb483343dc9/issue44-benchmark/benchmark.pdf).

I added the intermediate step that you asked for @gabrieleborg. I also plugged in some numbers that seemed reasonable and got an estimate of `.11`. Larger than our estimate, but not by a lot. There is a lot of room of improvement here, specially by changing numbers for others we believe in! (fyi @diegogentilepassaro)

**Comment by gabrieleborg** [comment]
Thanks @santiagohermo  that's amazing! yeah it's larger but this is literally the first try. I'll keep thinking on how to improve it too!!! vamos!

**Comment by santiagohermo** [comment]
Hey @gabrieleborg @diegogentilepassaro! I fixed the derivation a bit: [new pdf file here](https://github.com/diegogentilepassaro/min_wage_rent/blob/f3e413f5716299d57fe0a68452462d1876d8ec74/issue44-benchmark/benchmark.pdf)

I was making a mistake before and _not_ using constant elasticity functions. I fixed that and now the expression for elasticity does not depend on the MW to rent ratio (this is the only difference). I think this makes sense, because if functions are constant elasticity then levels shouldn't matter!

The MW to rent ratio is higher than 1, and it was increasing our estimate. Because we are not multiplying by it anymore, the estimate went down to `0.045`. Looking forward to using better values for our parameters!

**Comment by gabrieleborg** [comment]
That is perfect @santiagohermo because I am experimenting with the benchmark right now! I will update my code accordingly ;)

**Comment by santiagohermo** [comment]
One paper that estimates income elasticity of housing in the rent market @gabrieleborg: https://www.sciencedirect.com/science/article/pii/0094119081900309

Kind of old but a good start

**Comment by santiagohermo** [comment]
New pdf after minor fixes: [benchmark.pdf](https://github.com/diegogentilepassaro/min_wage_rent/blob/c029ad583959adcf7149794a241ef32056e8d11d/issue44-benchmark/benchmark.pdf)

**Comment by santiagohermo** [comment]
Thread follows in #45
