### ISSUE TITLE
Add controls for Economic shocks

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#50]
**Goal**
We want address the potential threat to identification arising from unobserved economic shocks correlating with both changes in MW and in rents. 

**Steps**
1. Identify controls that we can add to our main specification (e.g QCEW at the county-quarter level, the CPS at the msa-month level)
2. re-estimate main specifications with new controls

**Comment by gabrieleborg** [comment]
Guys! @diegogentilepassaro @santiagohermo 

In a first pass of this issue I started adding quarterly census employment and wages data to our analysis, and used them as county-level controls in our specifications. 

First, in [`base/qcew/code/make_county_month_panel.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/base/qcew/code/make_county_month_panel.do) I create a county-month panel with 3 types of variables: 

1. number of establishment by industry (quarterly measure)
2. number of employed workers by industry (monthly measure)
3. average weekly wage by industry (quarterly measure)

For the moment, I selected the following industries: 

- Federal Government (this is not exactly an industry, which are by definitions in the private sector, but I just classified them in the same categorical variables)
- State Government (see note above)
- goods-producing
- natural resources and mining
- construction
- manufacturing
- service-providing
- trade, transportation and utilities
- information 
- financial activities
- professional and business services 
-education and health 
- leisure and hospitality

Then, in [`derived/zipcode_month/code/create_final_panels.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/derived/zipcode_month/code/create_final_panels.do) I added all this variables. [In `analysis/first_differences/code/preclean.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/analysis/first_differences/code/preclean.do) I added  their log values to the final panel. In this way we are able to control for the percentage change in our first difference specification. For the moment i didn't compute shares out of total employment for simplicity, but we can do that as well. 

In [`analysis/first_differences/code/first_differences`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/analysis/first_differences/code/first_differences.do) I finally added a 4th column in both the static and dynamic table where I control for (the first diff) of all those variables.

_Static Specification_
<img width="522" alt="Screen Shot 2020-10-01 at 8 56 17 AM" src="https://user-images.githubusercontent.com/30894427/94811943-0ce8f880-03c4-11eb-983e-5ef647c220fa.png">

_Cumulative Dynamics_
<img width="514" alt="Screen Shot 2020-10-01 at 8 58 06 AM" src="https://user-images.githubusercontent.com/30894427/94812078-3d309700-03c4-11eb-8079-ec4220568cf4.png">


Lucky us, results are super robust to such inclusion! the SE of our estimates actually decreases slightly😁 (even in the 5 leads and lags spec, where the 5-period lags becomes significant at the 10 percent level, the actual point estimate gets smaller). This means that the effect we capture is not correlated with county-level economic trends proxied by employment and wages (e.g. if an area becomes attractive for tech firms leading to higher employment and wages,  and higher housing demand at the same time). 

I also started looking for other data sources: there's the Local Area Unemployment Data at the county-month level that we could retrieve but: a) it very hard-to-retreieve data as data before 2019 are disseminated on state websites in wildly inconsistent format; b) we are already controlling for changes in employment in many sectors so that measure would probably be correlated with the controls we already have. Let's talk about this and let's decide what to do. 

I am thinking right now what other type of control we could add, so I am eager to hear your take on this 😊.

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro hi guys! 

I have updated the analysis with controls following our discussion, and I kept exploring how we can make our case stronger with further controls. In [`analysis/first_differences/code/first_differences.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/analysis/first_differences/code/first_differences.do) I have split the results (both static and dynamic) in two tables: the first one remains as the original one, where we show the robustness of our results while including linear and quadratic zipcode trends. Then I created a table showing in each column what happens when we control for different county-level controls for economic shocks that may be correlated both with our dependent variable and our treatment variable. As we discussed, I think this structure will serve us better in the exposition of what possible threats our identification could face, and how our results appear robust every time we control for those. In the first column I reproduce the final specification of the original table, namely the most robust one including linear and quadratic zipcode trends. 

In addition to the economic controls from the QCEW (number of establishments by industry, employment by industry and weekly average wage by industry), I downloaded additional data from the Survey of Construction. Specifically, I downloaded _county-month_ data from the [_Building Permit Survey_ (BPS)](https://www.census.gov/construction/bps/about_the_surveys/). As you can read, this provides national, state, and local statistics of new privately own residential constructions. This relies on all places in US that requires a permit to build something new, and they say that 98 percent of privately-own residential building in US is in these areas. I manually downloaded the data in `drive/raw_data/bps/`, while you can find the official description of the data in [`raw/bps/cntyasc.pdf`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/raw/bps/cntyasc.pdf). The survey provides info about the number of _buildings, units, and permit valuation_ by size of the structure. The "sizes" are: 

- 1 units buildings (single family houses)
- 2 units buildings
- 3-4 units buildings
- 5+ unit buildings 

These information might help us proxy for unobserved shocks coming from the housing market, and that might not be captured by our previous economic controls. Even if we don't see, for example, an increase in employment or in the number of establishments, there could be in certain areas legislative effort to attract residents translating in improved working condition (i.e. higher MW) and higher housing demand. By controlling for the number and value of new permits issued we could hopefully address this concern. As always, I think that however we need to discuss this together to fully develop this argument because I might miss something (I thought about the bad control issue, but it doesn't strike me as super likely in this context).   

I create the dataset in [`base/bps/code/make_bps_cty_month.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/base/bps/code/make_bps_cty_month.do). Since our Zillow series contains single family houses and condo/coop (which are not mentioned in the BPS docs I have read so far), for the moment I only keep values for the 1 units buildings when saving the dta file. I then updated [`derived/zipcode_month/code/create_final_panels.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/derived/zipcode_month/code/create_final_panels.do) by adding a function that allows you to choose which extra data (demo, econ controls, housing permit controls) you want to add to any of our final panels. 

Finally, in [`analysis/first_difference/code/first_difference.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/analysis/first_differences/code/first_differences.do) I create the two sets of tables I told you before: 

_Static Model_
<img width="673" alt="Screen Shot 2020-10-03 at 1 00 17 PM" src="https://user-images.githubusercontent.com/30894427/94997335-685be780-0578-11eb-8ac9-73e92a246d6d.png">

_Dynamic Model (leads and lags)_
<img width="678" alt="Screen Shot 2020-10-03 at 1 02 25 PM" src="https://user-images.githubusercontent.com/30894427/94997382-bc66cc00-0578-11eb-813c-beb035c2cbf7.png">

As you can see our results are robust to the progressive inclusion of all controls. Not all counties were present in the BPS survey, even though since it focuses on metro area most of our counties were covered. However you can see that we lose some 18k observation. This leads to an increase of the SE. In the dynamic version, as I told you before, once we start including economic controls the 5-period lag becomes significant even though smaller in magnitude. Once we add the housing controls however the pre-trend gets a bit more pronounced. I believe this is partly caused by the smaller sample size because however there's not a huge change in the dynamics, but I would like to discuss that with you. To visualize the results in the last table better, the updated code also creates a plot for all this model: 
<img width="924" alt="fd_models_control" src="https://user-images.githubusercontent.com/30894427/94997509-90981600-0579-11eb-871f-47d79bf0313e.png">

First, remind that for the moment I tested model with a progressive inclusion of controls, so the "building" series actually include all other controls too. As you can see, the only version that differs a bit from the baseline is the last one (associated with column 5 of the dynamic table).

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! 

It's very nice that you included those controls for building permits, and reassuring to see that the we are robust to them! Questions (for Thursday!):

- Do you know why we loose so many observations? Maybe this is not such a problem with the unbalanced panel.
- Are permits every zero? Maybe we loose the zeros when we take log.
- The bad control problem would arise if we believe that the minimum wage causes housing permits, right? I agree that this seems unlikely, specially in the short run, but we should state the caveats in the paper.

I'd be happy to review the additions in the branch later this week :)

**Comment by gabrieleborg** [comment]
Thanks for the comment @santiagohermo! Yes, let's discuss this on Thursday. Before that I will try to think about other test we can do to control for unobserved shocks!

**Comment by gabrieleborg** [comment]
Thread continues in #54
