### ISSUE TITLE
Update results // Improve presentation for paper

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#55]
**Goal**
Update results in `analysis` in the light of the recent improvements.

**Steps**

- re-run `derived/zipcode_month` to create clean version of both unabalanced, and balanced panels. 
- update and re-run `analysis/first_differences` using unbalanced version plus econ control. 
- update `analysis` to clearly separate between baseline spec (unbalanced) and robustness checks for sample representativeness (balanced panel, weights, etc) , and unobserved shocks (econ and housing controls).

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo 
morning guys, sorry I don't have much time to document carefully everything but I need to send the draft to Emily and Matt by Friday. 

After we merged all the big PR we had I started updating the results. First, I created [`analysis/first_differences_unbal`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2355-update-results/analysis/first_differences_unbal/code) where the `preclean.do` only preprares the unabalanced panel and the analysis automaically include cohort X time FE. In this way `analysis/first_differences` is cleaner, creates only one panel in the preclean and we keep different parts of the analysis separated. Second, I updated the code in `analysis/first_differences_wgt`, especially in the `preclean` so now all specifications match across these 3 main section of the analysis. 

I then run them all, and the  main takeaways are: 

- The unbalanced version, although confirming the results, it would be harder to present as baseline. This is because as I told you yesterday, the effect is still there even though a bit lower (like 1.8-2 percent as opposed to 2.5%). This makes it barely not significant in some of the controls we apply (some econ shocks, the AB test). If you compare the D.ln_mw coefficient with any leads or lags it is clear there's an effect, it's just that the SEs remain rather large and this doesn't help up
- the balanced panel results are clearly very similar. I think that therefore in the end we should go wth this as baseline. I will expain the balancing procedure in the data section, and then in the robustness checks I will explain the potential shortcomings and show the consistency with the unabalanced panel results. 
- The weighted results are consistent if not slightly higher, but they give us a strong check as they also show smaller SEs. I will also present them in the robustness section.

**Comment by gabrieleborg** [comment]
Morning guys! @diegogentilepassaro @santiagohermo! 

I have worked quite a bit with `analysis` in order to get the draft done, so I'd figured I should post an update here on what I have changed. Then we can decide what to do (for more of a general discussion, see my post on #39 [here](url)). 

First, to our `baseline` analysis ([`analysis/first_differences/`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2355-update-results/analysis/first_differences)), I added two new folders, one for each sample restriction test we do: [`analysis/first_differences_wgt/`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2355-update-results/analysis/first_differences_wgt), and [`analysis/first_differences_unbal/`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2355-update-results/analysis/first_differences_unbal). In each of these 3 folders, I then split heterogeneity analysis from the normal. The script are now called: `estimate_base.do`, and `estimate_heterogeneity.do`. These, along with `preclean.do` are the most similar across the 3 versions. Indeed, we could think about moving `preclean.do` in `derived`. The only differences are that in [`first_differences_unbal/code/preclean.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2355-update-results/analysis/first_differences_unbal/code/preclean.do) we use the unbalanced panel, and that in [`first_differences_wgt/code/preclean.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2355-update-results/analysis/first_differences_wgt/code/preclean.do) we additionally create weights.

I then added, only in `first_differences_unbal` and `first_differences_wgt`, an extra script called `comparison_baseline.do` ([link1](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2355-update-results/analysis/first_differences_unbal/code/comparison_baseline.do); [link2](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2355-update-results/analysis/first_differences_wgt/code/comparison_baseline.do)). Here I create the appendix table where we compare results from our baseline sample with those of each of the specifications. The design of these script is not optimal in that they both use the "precleaned" version from the main analysis (i.e. the output of `first_differences/code/preclean.do`). Let's discuss on how to improve this. 

I then added, in [`first_differences_unbal/code/estimate_base.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/9a9409a4a964dc1af7d1046cbcf8512d472f9e35/analysis/first_differences_unbal/code/estimate_base.do#L249) and [`first_differences_wgt/code/estimate_base.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/9a9409a4a964dc1af7d1046cbcf8512d472f9e35/analysis/first_differences_wgt/code/estimate_base.do#L253) an extra plot comparing the dynamic model with sample restriction with our baseline one.  

Last thing to note, each version compute all models both **without** and **with** econ controls. Right now we only show econ controls for our baseline version, but if asked (needed) we can add tables with either weights or unbalanced panel **and** econ controls in appendix.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg I am happy with your great work here so feel free to send to PR!

**Comment by gabrieleborg** [comment]
Thread follows in #56
