### ISSUE TITLE
Add benchmarking exercise to paper

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#57]
[OVERVIEW]
Recently, @gabrieleborg sent [this draft](https://www.overleaf.com/project/5f7f85c09145600001f56689) with initial results to his committee. 

Per https://github.com/diegogentilepassaro/min_wage_rent/issues/39#issuecomment-712258862, in this issue we want to add an initial version of the benchmarking exercise to the draft.

[STEPS]

1. Move draft from Overleaf to repo.
2. Add model and benchmarking exercise to draft.

**Comment by santiagohermo** [comment]
Hey @gabrieleborg @diegogentilepassaro. I finished a first pass in this issue. I branch `issue57-benchmarking_paper` I did the following:

- Removed old folders related to event studies and older versions of the paper

- Added the last version of the paper to the [`paper` folder](https://github.com/diegogentilepassaro/min_wage_rent/tree/7fbe823bc14c0a602ae56982d07e5e89b50ad6ea/paper). Since we have a decent version already, I think that it makes sense to directly make changes and additions there (instead of starting over each time). I'm editing it with TexStudio, but I pressume that linking to overleaf or using some other tex editor would work as well. A few things:
   - I copied files in the [overleaf](https://www.overleaf.com/project/5f7f85c09145600001f56689) and changed figures and tables to point to the correct file. There are a few that point to the auxiliary folder `paper/input` which have to be fixed.
   - To make the files more menable to github (to see diffs and stuff like that), I manually wrapped lines to a roughly constant length. I'm not sure if this would be efficient though. We can easily change this convention if it's not.
   - I changed the convention for notes under table/figures, making the width constant throughout the paper.
   - Few other things to improve in the paper:
      - Fix descriptive table. I had manually changed it in the overleaf tidy it up. I think we should change  the code so that it's tidier already when it's produced
      - Finish up discussion section
      - Change figures 2 and 3 so that they have the same style. I.e., same coloring pattern and same distance between dots.

- Added an initial version of a model and benchmarking exercise, similar to what we already had.
     - In section 2 - model we introduce the general framework and argue that supply and demand forces should end up in a positive pass-through.
     - In section 5.4 we assume that functions are constant elasticity and use the model to benchmark our estimates.

Overall, I think that the paper is looking pretty nice guys! :muscle:

Questions and things to improve in the model/benchmarking front:

- Do we want to add derivations? I think it is not necessary (as they are not hard), but I don't feel strongly about it.
- I added some ["extensions"](https://github.com/diegogentilepassaro/min_wage_rent/blob/7fbe823bc14c0a602ae56982d07e5e89b50ad6ea/paper/02model.tex#L62-L77) to the model which require some work.
- To [construct the benchmark](https://github.com/diegogentilepassaro/min_wage_rent/blob/7fbe823bc14c0a602ae56982d07e5e89b50ad6ea/paper/05results.tex#L303-L309), I used the made up values we were using in [the note](https://github.com/diegogentilepassaro/min_wage_rent/blob/7fbe823bc14c0a602ae56982d07e5e89b50ad6ea/analysis/notes/benchmark.pdf). We should improve here by using values from the literature for the elasticities and our data for the share of minimum wage households.

**Comment by diegogentilepassaro** [comment]
Thanks for the great work @santiagohermo! It s looking great. As for things to improve and questions:

- Probably derivations in the appendix is useful. 

- The extension about quality seems like something quite important. If you want we can discuss a bit together and layout a plan for me to also take a look at this and help. 

- I totally agree that we should take the numbers from the literature and from our (weighted) data. Let's discuss this in the next meeting so that we open a new issue for this.

**Comment by gabrieleborg** [comment]
Thanks @santiagohermo !!! 

So just to clarify, I was editing the data section adding a more detailed description of the Zillow data. Shall I do it in this branch?

**Comment by santiagohermo** [comment]
Absolutely!

**Comment by santiagohermo** [comment]
Thread continues in #63
