### ISSUE TITLE
Composition Bias

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#58]
**Background**
changes in rents may be caused by changes in the underlying composition of rentals in a given zipcode (entry and/or exit of different units). This might be correlated with unobserved determinants of MW changes and therefore bias our results. 

**Goal**
Address the composition bias issue both analytically and theoretically. 

**Steps**

1. Add listing inventory time-series to main dataset
2. perform "placebo" regression on such outcome
3. update Overleaf draft with better explanation of our dependent variables's strengths and theoretical motivation

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro, 

I started running some analysis replicating our models while using the (log) number of listings in the Zillow inventory as dependent variable. 

First, in [`derived/zipcode_month/code/create_final_panel.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2358-composition-bias/derived/zipcode_month/code/create_final_panels.do) I add to the final dataset the following variables: 

- number of listings sfcc
- number of new listings sfcc 
- list price sfcc (temporarily, to experiment)

I then created a new `analysis` folder called `first_differences_nlist`, where once again we have one [`preclean.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2358-composition-bias/analysis/first_differences_nlist/code/preclean.do) very similar to the others, and an [`estimate_compbias.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2358-composition-bias/analysis/first_differences_nlist/code/estimate_compbias.do). Here I replicate the usual analysis, by estimating all our static and dynamic models but using the log of the number of listing as dependent variable. 

Here are the main dynamic coefficients:
<img width="924" alt="fd_models_nlist" src="https://user-images.githubusercontent.com/30894427/97056768-c23c4580-1557-11eb-868c-a9d47a3d03b5.png">

the coefficients are almost never significant. However, they "jump around" a bit. Additionally, it looks like there might be some minor concerns about potential anticipation of the MW change, as shown by the increase in listings 3 months before the change. 

I also quickly run the analysis on the "unbalanced panel" (even though i haven't uploaded the scripts yet): 
<img width="924" alt="fd_models_nlist_unbal" src="https://user-images.githubusercontent.com/30894427/97056963-32e36200-1558-11eb-8b7f-6e0337706c80.png">

Here you can see that there's a change in the pre-trend dynamics, suggesting how the previous' one was at least partly driven by sample selection. Here instead it looks like, starting from month t - 3, the number of listings diminishes before the MW change. In any case, also here there's only 1 coefficient barely significant at the 10 percent level (t - 1), but in general the plot doesn't indicate any conclusive evidence of a possible effect of MW on the number of listings (and even if mildly, remember that we are talking about listing inventory, not rentals so there's also this caveat to specify)

**Comment by diegogentilepassaro** [comment]
Thanks @gabri! A few follow up questions an comments: 

- How does it look the result from our first differenced static model on this number fo listings variables? 

- Can we have some notion of quality of the listings? For example can we create some variable that is average price per listing? 

- Feel free to send to PR and I will be happy to take a look and play around with the code!

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro: 

- here are the result from the static model (both baseline, and when additionally controlling for local shocks): 
<img width="814" alt="Screen Shot 2020-10-26 at 11 26 32 AM" src="https://user-images.githubusercontent.com/30894427/97192493-54259780-177e-11eb-8cc3-54de147bcea9.png">

As you can see, the point estimate is positive and large I would say. However the SEs are also quite large, and they are consistently so when you look at the dynamic plot. 

- Yes, we do have the median listing price (not the average). Here's what happens when I additionally control for median listing price (disregard the last coefficient, which is indeed the one for ln_med_list_psqft_sfcc): 
<img width="924" alt="fd_models_nlist" src="https://user-images.githubusercontent.com/30894427/97192880-c0080000-177e-11eb-8f39-2e85d010a056.png">

- Ok, I want to play around a bit more before PRing (namely, I want to check what happens to house prices estimates when I  weight for the inverse of the sample size).

**Comment by diegogentilepassaro** [comment]
Those tables look great @gabrieleborg! They seem like the placebo exercise that @santiagohermo had in mind and fortunately they show a no result that is pretty suggestive of inventory not jumping exactly at the MW changes.  

Something else to try: What happens if we run our baseline model (static version with rental prices as dependent var) and we directly control for the number of listings? 

As for the pending weighting idea: Not sure I understand what we want to do. Are you trying to re-run our baseline model with weighted data with the weights given by the inverse of the number of listings?

**Comment by gabrieleborg** [comment]
Thread follows in #61
