### ISSUE TITLE
LODES-based salience analysis

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#59]
**Goal**
Strengthen our identification and narrative about the mechanism by showing how the effect shows up also in non-treated zipcodes where MW workers from treated zipcodes live. 

**Steps**

1. For each event, compute for each zipcode A the share of MW workers that work in the treated zipcodes but live in zipcode A. 
2. For each zipcode, compute the "experienced MW": a weighted average of the MW based on where MW workers work. 
3. Analysis: what happens when you take into account "treatment intensity" as measured by either 1 or 2

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo first pass on the LODES update. 

Since this is a rather complex technical task, I am now posting an initial description of only a part of the whole exercise. Specifically, I have now built an origin-destination matrix at the USPS zipcode level. This lives in `base`: [`base/lodes/code/make_odmatrix_ziplevel.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2359-LODES-based-salience-analysis/base/lodes/code/make_odmatrix_ziplevel.R). 

First of all, the LODES data contained in the OD files are not as specific as the _Workplace Area Files_, or the _Residence Area Files_. This means that we cannot observe, as before, the number of workers earning less than $1250/month **and** 29yrs or younger. In the OD files you can only observe **either** one or the other characteristic. 

The main difficulty of this exercise is that the matrix (which is actually composed by many state-level files) comes at the block level and needs to be aggregated. I adopt the following steps for each state separately (with `lapply()` in R):   

1. I collapse the count of _total jobs_, _low income jobs_, and _younger workers jobs_ at the tract level. This is done because our main crosswalk to get to USPS zipcode is a tract-zipcode crosswalk. This can only be done in a 2-step procedure: 
    - for each _origin_ block, sum target counts by _destination_ tract.
    - for each _destination_ tract, sum target counts by _origin_ block. 
2. Now that we have a tract-level od matrix, I replicate the same procedure using the tract-zipcode crosswalk with the only difference that now instead of taking the sum, I take a _weighted sum_ using the provided weights:  
    - for each _origin_ tract, weight sum target counts by _destination_ zipcode.
    - for each _destination_ zipcode, weight sum target counts by _origin_ zipcode. 

I finally save each state zip-level od matrix separately because of size: if we append them all together we would have a 34M rows dataset. 

Given these files, my plan is now to compute, for each period in our sample: 
1. the share of treated workers (both overall, and young or low income)
2. the experienced MW based on the share computed in 1) and the MW the workers face in the zipcode they work in. 

I think that after computing such measures, we will be in a good position to test many assumptions since we will be able to identify, for example, zipcodes that are not directly treated but that nevertheless have a positive share of treated workers. 

Let me know if this all makes sense, and If you have suggestions/questions!

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo 

The first pass of results is here. Just to quickly recap, I started creating 3 variables for _experienced MW_: 

- using the shares of workers in other (and self) zipcode; 
- using the shares of young  workers in other (and self) zipcode. 
- using the shares of low income workers in other (and self) zipcode; 

In the end, I don't think it makes much of a difference because the measures are highly correlated (you can't read the labels but the order is the one I used above here): 
![Screen Shot 2020-10-30 at 9 20 14 AM](https://user-images.githubusercontent.com/30894427/97759403-5584f600-1ad7-11eb-81bd-7b912a71ce8e.png)
As you can see, there's also very high correlation with the classic mw variable. I suspect this originates from the fact that, since most of our variation comes from state-level changes and therefore most of the time ALL zipcode where workers go are treated at the same time. Probably to validate our design we should restrict the analysis to subsets of zipcodes with particular characteristics (i.e. border zipcodes), but I still haven't thought much about it (and how long it will take). 

When we switch to experienced mw, our panel changes: we now have more treated units at any time t, even though the changes mw will be smaller for such units (since share of treated is less than one). Specifically: 
![Screen Shot 2020-10-30 at 5 47 54 PM](https://user-images.githubusercontent.com/30894427/97759765-0b504480-1ad8-11eb-9435-e6c3896d9290.png)
As I anticipated you yesterday, most of those changes are very very small (the difference in the number of obs comes from the fact that in the previous count Stata also includes the missing first obs for each zipcode): 
![Screen Shot 2020-10-30 at 5 49 10 PM](https://user-images.githubusercontent.com/30894427/97759843-38045c00-1ad8-11eb-93b5-e4c4e08cd7ac.png)

As Santi rightly pointed out I think, what we have now is that we are reducing measurement error in our explanatory variable. I think that theoretically we can now do 2 things: 

1. Re-estimate the model with the new _experienced MW_
2. Estimate the differential impact on units that are only _indirectly_ treated (i.e. positive Dln_expMW but Dln_MW equals zero), as opposed to _directly_ treated. 

**1. Re-estimate the model with new _experienced MW_** 
This is the simplest exercise. When replacing the main explanatory variable we get: 
<img width="534" alt="Screen Shot 2020-10-30 at 6 05 23 PM" src="https://user-images.githubusercontent.com/30894427/97760837-831f6e80-1ada-11eb-8e92-d4a7c001afc7.png">
![image](https://user-images.githubusercontent.com/30894427/97760994-ef9a6d80-1ada-11eb-8d26-335c20627c69.png)

Results confirm our intuition: estimates are more precise. We have to think however if the identification conditions have changed and what this result implies more generally. 

**2. Estimate the differential Impact**
This is a more complex exercise. As a first pass, I created a categorical variable identifying, for each period t, 3 groups: non-treated (control), treated _indirectly_, and treated _directly_. I then interact our main treatment variable, D.ln_exp_mw with this categorical variable, similarly to what we have done with our heterogeneity analysis. One point that I am not sure still is the fact that, even though this is clearly a categorical variable, it varies in time. However, I think conceptually it works like the periods fixed effects: they also change (be definition) in every period, but you still want to include them as they now identify the "category" associated with that specific difference. If before we had, for example,  the categories _year_=2012 and _year_=2013, now we will have the categories _year_=11/12 and _year_=12/13. I would like to hear what you think about this (specifically, is it ok to still keep 3 categories, or we need to switch to 5 i.e from _untreat_ to _direct treat_, from _untreat_ to _indirect treat_, and so on). 
<img width="598" alt="Screen Shot 2020-10-30 at 6 21 13 PM" src="https://user-images.githubusercontent.com/30894427/97761681-b662fd00-1adc-11eb-8594-041c0601c44b.png">
As you can see, the effect increases in general. I am still unclear why (maybe the specification is simply wrong). More surprisingly, the effect in the _indirect_ treated zipcodes is double the _direct_ one! At first sight, it didn't make much sense to me, but then I recalled Matt's comment: 
_On the basis of Jorge's JMP, what the LODES data should show is that low wage workers commute AWAY from minimum wage increases. In your exercise, this implies that zip codes that experience a MW increase but are close to a zip code (state) that does not, should see smaller rent increase than interior zip codes.  If you found this, it would be really neat. Using the LODES data to pin down pairs of cross-border zip codes where you could look for this would be really great._

This is not exactly what he meant, but in a sense I think that if we apply that logic the explanation is that te _indirectly_ treated zipcodes are most likely zipcode close to the treated one and the former, according to Jorge's paper, should see a higher rent increase. Of course, that's a rather articulated reasoning, but maybe it's worth investigating it.

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo I extended the logic of the previous comment, and estimated the differential effect in the dynamic model. For sake of clarity, I have written this note to better explain the logic behind what I am doing: 
<img width="575" alt="Screen Shot 2020-10-31 at 4 07 13 PM" src="https://user-images.githubusercontent.com/30894427/97788950-25029200-1b93-11eb-9ad4-8bdd26e321a0.png">

Following this, this is what I get: 
<img width="924" alt="fd_models_expgroup" src="https://user-images.githubusercontent.com/30894427/97788967-4499ba80-1b93-11eb-9f78-dfba47591348.png">

Results for the direct effect are neat. Results for the indirect group are more noisy. In the pre-trend, they move around a bit, but you can clearly notice a jump at t=0. As for the directly treated ones, the impact is concentrated mostly in t=1 and t=1. However, we have a weird t=3 coefficient. I am thinking what could cause that (maybe it'd be interesting to run this on the unbalanced panel). 

Overall results confirm what we can see from the static model: the effect seems to be larger in indirectly treated units. This is at first surprising...but I think we want to consider also the underlying treatment variance (larger), its mean (way smaller) and the fact that the share of treated workers is generally very small in these zipcodes, so the overall incidence (as Matt would put it) is probably small. 

One last thing: you may notice that the static estimated I posted are lower. This is because there I didn't include group-level trends as I did in the dynamic model. If I do that, we get perfectly consistent estimates.

**Comment by santiagohermo** [comment]
That's really cool @gabrieleborg!  I feel like this experienced MW idea is really going to pay off.

Your first explorations are quite nice. Some comments:
- It's really cool that replacing the mw variable increases the effect.
- Not sure if I understand the treated/untreated fully. But anyway, some reactions:
   - Matt and Jorge Perez's story is that untreated zipcode will experience some effect due to people's migration. Does it imply that the effect should be larger? That's unclear to me.
   - It might be that untreated zipcodes do have larger measurement error in their mw variable. As you show in your first comment, a lot of places have a tiny increase in the experienced MW. I think it would be useful to establish a cut-off or something to get rid of those, either in the shares when constructing the variable or the variable directly.

Given that this is a hard-to-implement computation (thanks for the amazing effort Gabri!), I would suggest that we review it asap to make sure everything is right; and we open a follow-up to nail down a nice way to incorporate this to the paper + understand what identifying assumptions are required.

**Comment by diegogentilepassaro** [comment]
Thanks for the great work @gabrieleborg! We are really making moves here :D

A few comments/questions:

1. I am not sure I understand what are the weights that you describe in 2. [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/59#issuecomment-718032220). Are they population based? Housing units based? Something else? 
2. As for re-estimating the model using experienced MW, it looks like we are doing what we should and we are lucky taht results make sense and look neat 👍 
3. As for estimating the differential Impact things are much more complicated. In fact, it is not clear to me that we are doing the right thing. Interacting the experienced MW with a dummy for whether the zipcode is directly or indirectly treated seems really weird because the dummy is a function of the experienced MW. Two things to try come to mind: 
    - (i) Estimate the model using experienced MW for each of the 2 samples **separately**. We should see that there is a bigger effect in the direct than in the indirect.
    - (ii) To think about this more carefully some diagnostics could be to answer: What happens if we throw into the model dummies for each group, experienced MW, and then the interactions? Are they all identified or things drop out? 
4. I am not 100% sure I understand Matt's comment yet, but we should definitely try to be sure we do. Let's discuss it tomorrow!

**Comment by gabrieleborg** [comment]
@santiagohermo  @diegogentilepassaro thanks for comments. Sending this to PR for review in a moment. 

Answering Santi: 

After thinking a bit more about Matt and Perez's story, I am not sure anymore we should indeed expect a higher impact. In that paper he actually says that MW workers will change their _workplace_ location, if living close to a non-treated area, but he doesn't address residential choices (I believe). So a priori it's difficult to anticipate whether the effects shall be larger or smaller. Generally speaking, I believe that the effect should simply reflect the presence of MW workers living in not treated zipcodes.

answering Diego: 
1. the tract-zip crosswalk uses population weights
2. 👍🏽
3. Agree, we need to think about this! I am not sure I follow your second point, let's discuss it tomorrow!
4. see my reply to Santi.

**Comment by gabrieleborg** [comment]
Thread continues in #68
