### ISSUE TITLE
Estimate our baseline models with more aggregated data and compare it with our estimates 

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/min_wage_rent#66]
[Goal]
Understand clearly how to compare our result with Tidemann and Yamagishi, and what are the advantages of our paper over theirs.

[Steps]
1. Construct year-zipcode, month-county, and year-county data.
2. Estimate  our baseline model in those datasets.
3. Report, compare with our estimates, and conclude. 

[Notes]
- Not sure if we want to aggregate our zipcode-month data in all cases. For example, for the zillow variables we could just download county-month data as well. For the MW data we can just use the raw data before implementing our crosswalks that transforms it to zipcode. 
- Seems like aggregating on the time dimension is less of a problem than aggregating on the geographic dimension, although still tricky because the median of a month doesn't have a clear relation with the median of a year.

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg I have opened this issue to start thinking about the comparison of our paper with Tidemann and Yamagishi. Please let me know your thoughts!

**Comment by gabrieleborg** [comment]
Thanks @diegogentilepassaro for setting this up! 

I think a good starting point would be to compute a county-month model, and eventually add a county-year one. 

In terms of data, I downloaded already the county-level data for our preferred series, sfcc (note that in the raw data is called allHomes). In this way I think it would be easy to do both exercise: aggregate our zipcode-month data, and once we have a county-month panel, add the Zillow county-month series so we can easily test both. 

For the MW changes, I think we can also adapt our setup pretty quickly. For the state and county level MW changes there's no problem. For the city level changes, I have downloaded a place-county crosswalk (you can find it in `raw/crosswalk/place_county_xwalk.csv`) so we can compute, for each city that had MW changes, how much does that affect each county that the city itself span.

**Comment by diegogentilepassaro** [comment]
As per meeting:

- We will start with estimating our model with data at the county-month. For rents, we will use Zilllow data that directly come at the county-month. For MW, we will use ur raw data to construct county-month measures. We will not use our zipcode-month panel at all as aggregating a median is complicated, and assigning MW changes based on that will have more measurement error.

**Comment by santiagohermo** [comment]
I made a simple simulation to play with the median of full data vs mean of medians issue, @diegogentilepassaro @gabrieleborg . See the plot below where:

- Each point shows (mean of medians of subsamples, median of full data)
- Dotted line is the 45* line
- Dashed lines are max and min across medians of subsamples

![Rplot](https://user-images.githubusercontent.com/45404755/98030113-88343480-1dde-11eb-8713-08a510b46f92.png)


I think this suggests two conclusions:
 
- the avg of medians and the median of the overall data are strongly correlated, 
- the avg of medians seem to fall within the medians of all groups



<details><summary>CODE</summary>
<p>

```R
set.seed(42)

means       <- c()
medians     <- c()
max_medians <- c()
min_medians <- c()

for (rep in 1:50) {
  x <- rnorm(50, mean = 5, sd = 2)
  y <- rnorm(50, mean = 2, sd = 3)
  z <- runif(50, min = 0, max = 6)
  
  medx <- median(x)
  medy <- median(y)
  medz <- median(z)
  med_full <- median(c(x, y, z))
  mean_meds <- mean(c(medx, medy, medz))
  max_medians <- c(max_medians, max(medx, medy, medz))
  min_medians <- c(min_medians, min(medx, medy, medz))
  
  print(sprintf("Full median: %s. Median of subsamples: (%s, %s, %s). Avg of medians: %s",
                round(med_full, 2), round(medx, 2), round(medy, 2), round(medz, 2),
                round(mean_meds, 2)))
  
  means   <- c(means, mean_meds)
  medians <- c(medians, med_full)
}

library(ggplot2)
ggplot() +
  geom_point(aes(x = means, y = medians)) +
  geom_line(aes(x = means, y = max_medians), linetype ="dashed", alpha = 0.8)+
  geom_line(aes(x = means, y = min_medians), linetype ="dashed", alpha = 0.8) +
  geom_abline(intercept = 0, slope = 1, linetype ="dotted") +
  xlim(2.5, 4.5) + ylim(1, 5.5)
```
</p>
</details>

**Comment by diegogentilepassaro** [comment]
❤️

**Comment by diegogentilepassaro** [comment]
@santiagohermo just checked the code for the simulation.

- Il'll buy your second conclusion: the avg of medians seem to fall within the convex hull of medians of all groups. 
- The avg of medians and the median of the overall data may not be very correlated.


<details><summary>CODE</summary>
<p>

```R
set.seed(42)

means       <- c()
medians     <- c()
max_medians <- c()
min_medians <- c()

for (rep in 1:50) {
  x <- rnorm(50, mean = 5, sd = 2)
  y <- rnorm(50, mean = 2, sd = 3)
  z <- runif(50, min = 0, max = 6)
  
  medx <- median(x)
  medy <- median(y)
  medz <- median(z)
  med_full <- median(c(x, y, z))
  mean_meds <- mean(c(medx, medy, medz))
  max_medians <- c(max_medians, max(medx, medy, medz))
  min_medians <- c(min_medians, min(medx, medy, medz))
  
  print(sprintf("Full median: %s. Median of subsamples: (%s, %s, %s). Avg of medians: %s",
                round(med_full, 2), round(medx, 2), round(medy, 2), round(medz, 2),
                round(mean_meds, 2)))
  
  means   <- c(means, mean_meds)
  medians <- c(medians, med_full)
}

library(ggplot2)
ggplot() +
  geom_point(aes(x = means, y = medians)) +
  geom_line(aes(x = means, y = max_medians), linetype ="dashed", alpha = 0.8)+
  geom_line(aes(x = means, y = min_medians), linetype ="dashed", alpha = 0.8) +
  geom_abline(intercept = 0, slope = 1, linetype ="dotted") +
  xlim(2.5, 4.5) + ylim(1, 5.5)
```
</p>
</details>

**Comment by santiagohermo** [comment]
Nice example @diegogentilepassaro! I noticed that your 4 sets of data do not share support at all. Maybe a condition for mean of medians and medias of whole data to be correlated is something about overlapping supports? Impossible to verify given that we don't observe raw postings.

**Comment by gabrieleborg** [comment]
Thanks for these helpful exercises guys! @santiagohermo @diegogentilepassaro 

I just wanted to point out that the support is likely to be very similar, but not necessarily identical. This is because I suspect that, when reporting zipcode-level median rents, certain zipcodes might be discarded if they don't have enough listings due to privacy reasons (I cannot find the reference on their website). If that's the case, then by definition the discrepancy between the underlying listings in the zipcode and county-level dataset is going to be relatively small. This also means that, if anything, the county-level median will be based on more listings than the zipcode one.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg and @santiagohermo, in the end, I had to change the approach a bit. Long story short, there are USPS zip codes that are more than the ZCTA ones, therefore there are several ZCTA codes that share the same USPS zip code. I ended up keeping all the USPS_ZIP-ZCTA matches because I didn't even know how to chose among them and because if we lose USPS zip codes we lose the ability to match the already scarce Zillow zip code data points.

This in turn caused me to think that we can keep the whole ZCTA-county-place combinations as well. Therefore I output a crosswalk that has all ZCTA-USPS_ZIP-county-place combinations. Those combinations are such that there are 32681 unique ZCTA's that cover the whole US. What do you think about this approach? 

The to-do list:
- We need to think about how to match the Zillow and MW data now. The other data we will match without issues with the ZCTA's. 
- We need to list all places in the repo where we will implement changes.

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro! I think your approach makes sense. That way, we can more flexibly choose what to keep to build different datasets (at the county level, zipcode level, etc).

Regarding next steps, I think it would be a good idea to PR this crosswalk and, after it's merged, open follow-up issues to:
- Split the zillow-mw step in two
- Apply the crosswalk in LODES
- If we need to update something else, open another issue

Later, we can update the panels used for estimation. What do you think? 
FYI @gabrieleborg

**Comment by diegogentilepassaro** [comment]
@santiagohermo, this plan sounds great! I will send this to PR now.
