### ISSUE TITLE
Implement new main table and figure

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#67]
[GOALS]
Per https://github.com/diegogentilepassaro/min_wage_rent/issues/39#issuecomment-721186499, we want to re-structure the presentation of our main results.

[STEPS]
1. Fix static table.
2. Change figure 1 to 2 panels.

**Comment by diegogentilepassaro** [comment]
@santiagohermo I will add here a step 1.5:

Add paragraph stating why we think of housing supply as fixed, and show building permits placebo.

**Comment by santiagohermo** [comment]
Hi @diegogentilepassaro @gabrieleborg! I completed a pass re-structuring the first differences folder and output (step 1 of the task).

- See [code](https://github.com/diegogentilepassaro/min_wage_rent/tree/5e30b9036aee1eaf55133e87c0a369fcffcc3a96/analysis/first_differences/code). I separated the production of figures from the main estimation.
- See [output](https://github.com/diegogentilepassaro/min_wage_rent/tree/5e30b9036aee1eaf55133e87c0a369fcffcc3a96/analysis/first_differences/output). We now produce `eps` format figures to include in the paper
- Following @diegogentilepassaro's approach in #60, I added the results to a [`staged_output`](https://github.com/diegogentilepassaro/min_wage_rent/tree/5e30b9036aee1eaf55133e87c0a369fcffcc3a96/paper_slides/staged_output) file [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/5e30b9036aee1eaf55133e87c0a369fcffcc3a96/paper_slides/staged_output/output.pdf). One minor thing I'm not sure about is what colors to use. I'll think about it more later.

Let me know what you think!

**Comment by gabrieleborg** [comment]
Thanks @santiagohermo!!! 

Two quick things: 

1. I am wondering whether it makes sense to consolidate the dynamic and cumulative effect of the dynamic table in just one output, by simply adding the estimated cumulative coefficients at the bottom of the dynamic table (I think Jesse suggested it once) ? 
2. Let's have a remainder to also update: `first_differences_wgt`, `first_differences_unbal` and `first_differences_nlist` once we decide which output we want from those part of the analysis (it can also be another issue, let's discuss it tomorrow I guess)

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! On your comments:

1. I think this is a great idea. I'll implement it
2. Sounds good. I think it's a good idea to start tackling those after our call

One thing I forgot to mention, I'm only using controls from the following industries: business services, information and manufacturing. (See [code](https://github.com/diegogentilepassaro/min_wage_rent/blob/5e30b9036aee1eaf55133e87c0a369fcffcc3a96/analysis/first_differences/code/estimate_base.do#L168-L177)). We can add some other controls if you think appropriate.

**Comment by santiagohermo** [comment]
I implemented fixes above @diegogentilepassaro @gabrieleborg. See [staged output](https://github.com/diegogentilepassaro/min_wage_rent/blob/c1480eb0e97f9c6ad84707f849d55a3c7fcc69a1/paper_slides/staged_output/output.pdf)

**Comment by santiagohermo** [comment]
I changed a bit more the formatting of tables. I changed digits of coefficients and added a separate panel for the cumulative sum. See [staged output](https://github.com/diegogentilepassaro/min_wage_rent/blob/428ffc1016d36c0db9cb03a3524c6838b00974ec/paper_slides/staged_output/output.pdf)

**Comment by diegogentilepassaro** [comment]
For reference see Figure 4 of [this paper](https://pubs.aeaweb.org/doi/pdfplus/10.1257/aer.20141702).

**Comment by santiagohermo** [comment]
Hey @diegogentilepassaro @gabrieleborg! I added the cumulative sum plots with confidence intervals

<details><summary>See figures</summary>
<p>

![fd_models_coeffs](https://user-images.githubusercontent.com/45404755/99406800-5500a380-28bc-11eb-8b69-5c6dd2f09098.png)
![fd_models_cumsum](https://user-images.githubusercontent.com/45404755/99406802-5631d080-28bc-11eb-9f58-ad0bdf9b368b.png)

</p>
</details>

I did not include the long-difference model though. I am not sure that this is what we want in this case. The paper mentioned [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/67#issuecomment-726337353)  estimates a long-difference as the baseline, and then runs "short differences" to construct the cumulative effect. We, on the other hand, are interested in the short run since our effect happens there.

What we might want instead is some regression that has the cumulative sum of coefficients as one parameter to estimate. I tried doing some math above but it was wrong (that's why the reverted commit). We should think how to pull this off a little bit more.

To illustrate how the "long-difference" doesn't work, take a look at the following regression:

<details><summary>Long-diff 5 months</summary>
<p>

![image](https://user-images.githubusercontent.com/45404755/99409320-3e0f8080-28bf-11eb-8578-6a0cb0373568.png)

</p>
</details>

Very similar results if we run differencing over two months:


<details><summary>Long-diff 2 months</summary>
<p>

![image](https://user-images.githubusercontent.com/45404755/99409533-7e6efe80-28bf-11eb-9f9a-3b3ac4a486db.png)

</p>
</details>

I think that this are alternative noisy estimates of our main effect. Any thoughts?

**Comment by gabrieleborg** [comment]
Thanks for the plots @santiagohermo !!! a few stylistic tips (we can do it later, but just to remember :D ): 

- remove unused legend notation in top figure 
- replace line with connected to show dots in bottom plot
- homogenize color for bottom plot (i.e. turn cumulative effect from green to blue as the CI) 

Regarding the long term difference, that's interesting. I didn't expect not to work. In any case I don't think It's a big deal. We shall simply report the cumulative effect in the downstream tables (either similarly to what you already did in the full dynamic table, as a statistics, or as we discussed in the past alongside the static one). I will start updating all results soon and I'll think about it a bit better. So we can settle on this during our next meeting !

**Comment by santiagohermo** [comment]
Thanks for the comments @gabrieleborg! I implemented those fixes. Regarding the color, it seems that I was using the wrong option to set the color of the line (`mcol` vs `lcol`), so it wasn't working before. Now it's fixed

Another comment is that these are all 90% CI

<details><summary>See figures</summary>
<p>

![fd_models_coeffs](https://user-images.githubusercontent.com/45404755/99420655-787f1a80-28cb-11eb-894e-d0b9237feadf.png)
![fd_models_cumsum](https://user-images.githubusercontent.com/45404755/99420657-79b04780-28cb-11eb-9f21-33e51bc6fa3c.png)

</p>
</details>

On the long difference. If you write down the equations is not easy to make a transformation such that one coefficient is the cumsum! I agree, probably it's not a big deal. The distributed lags model cumulative path doesn't look too bad.

**Comment by diegogentilepassaro** [comment]
Thanks for this @santiagohermo! Sorry to spoil the fun discussion but the reason the long-difference is not working is because we need to use lags not further differences. In code that would be:

`      eststo clear
	eststo: reghdfe D.`depvar' D.ln_mw,	///
		absorb(`absorb') vce(cluster `cluster') nocons
	eststo: reghdfe L5.D.`depvar' L5.D.ln_mw,	///
		absorb(`absorb') vce(cluster `cluster') nocons`

**Comment by santiagohermo** [comment]
Thread continues in #71
