### ISSUE TITLE
Collect feedback + plan semester

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#79]
We have started to receive feedback from the last draft. In this issue, we will:

- Collect all feedback from the last draft
- Apply easy corrections to paper based on feedback (like fixing typos and stuff like that) in a new branch
- Discuss research plan for this semester

**Comment by santiagohermo** [comment]
Comments from Jesse Shapiro:
[gentile-hermo-3yp.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5783617/gentile-hermo-3yp.pdf)
[gentile-hermo-3yp.txt](https://github.com/diegogentilepassaro/min_wage_rent/files/5783619/gentile-hermo-3yp.txt)

Comments from Neil Thakral:
[Santiago.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5783625/Santiago.pdf)

Comments from Matt Pecenco:
[Borgetal_comments.docx](https://github.com/diegogentilepassaro/min_wage_rent/files/5783629/Borgetal_comments.docx)

**Comment by santiagohermo** [comment]
Questions for tomorrow (fyi @diegogentilepassaro @gabrieleborg)

- Generally. Is the model worthwhile? While we find appeal in developing a full-blown model, we worry that it may take too much time. We could also leave this for a follow-up project. For discussion.
- For Jesse. We could include a more refined welfare argument. How would a computation of welfare look like without a model? (point 2 of his txt file)
- Other things to add? Housing values // Amenities?
- Can we control for the cyclicality of MW increases? We have an annoying -5 coefficient.

**Comment by santiagohermo** [comment]
Link for meeting today @diegogentilepassaro @gabrieleborg: https://brown.zoom.us/rec/share/z8t68qoHXHTqNGqGTH3tuU8U7kaJoBZ5cq-VQlLaAla8JW7lBDowBJ6tGdoFRKg9.9xbdpIUKke9j6AjY?startTime=1610139616000

I think it'd be useful to make a short summary of the talk's main takeaways. We have to meet to talk about next steps!

**Comment by santiagohermo** [comment]
Hey @diegogentilepassaro @gabrieleborg! I applied some of the obvious fixes following Neil's comments in a new branch. See annotated pdf marking stuff I implemented below:
[NTcomments_SH.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5793450/NTcomments_SH.pdf)

**Comment by santiagohermo** [comment]
Next steps @diegogentilepassaro @gabrieleborg.

We want to have a draft before May.

### Data
1. Make master crosswalk at the zipcode-place-county-state(-zcta?-msa?). 
   - Useful resource: https://mcdc.missouri.edu/applications/geocorr2018.html
   - Some code already exists for this, we need to create a new step in the repo and implement more carefully.
2. Separe minimum wage construction from zillow construction in `base`. Both will use the crosswalks created in 1.
   - `min_wage` should contain datasets at different geographies with relevant MW measures (e.g., including and excluding local changes for county mws). These data should be defined for the whole US
   - `zillow` should create datasets at the zipcode and county level. This would involve bringing in county-level Zillow data
3. Fix LODES to use master crosswalk created in 1. Similarly, update other steps that use it.
4. Fix county-month and county-quarter panels.
5. Do we need more data? Compare with controls in [Leung (2020)](https://www.mitpressjournals.org/doi/pdf/10.1162/rest_a_00915)

### Analysis
Points we want to implement eventually in the semester

- After data work is completed, compare to Tiedemann and Yamagishi.
- Spent some time thinking about the experienced MW. Consider using it as main specification
- Check heterogeneity based on announced/unannounced MW changes.
- Try model. Is it feasible? We will define on February 11th

**Comment by gabrieleborg** [comment]
Hi @santiagohermo @diegogentilepassaro :) 

I addressed most of JS comments. You can check my answers on [gentile-hermo-3yp_GB.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5905208/gentile-hermo-3yp_GB.pdf). If we then want to reverse some of the larger changes (e.g. I shrank the abstract), we can use the commits logs to restore text

As for the remaining ones: 

- check how to produce a MSA level scatter plot of annual changes for the correlation between Zillow and SAFMR to show positive correlation
- Data section: shall we place LODES description in subsection 2.3 at the top (since we just explained how we used LODES to build exp MW in the previous subsection)?
- Shall we move the financial sector stats to appendix with the other?
- Comment on page 14 about controls?
- Comment page 19: anticipatory effect might still be present even if the supply of houses for sale does not change (since they are equity, there may be appreciation). Shall we add a brief estimate on the impact of MW on house values? 
- Comment page 21: not sure how to comment that
- Comment page 30 (cumulative effect and magnitude of pass-thorugh): we need to have an answer for that

One last thing: for some reason I can't compile biblio references properly, so at the end you may want to re-compile the main.tex document.

**Comment by santiagohermo** [comment]
Thanks for [that](https://github.com/diegogentilepassaro/min_wage_rent/issues/79#issuecomment-770989342) @gabrieleborg! I completed a pass on your replies to JMS's comments. See [gentile-hermo-3yp_GB_SH.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5915976/gentile-hermo-3yp_GB_SH.pdf). I responded to the points you flag in the pdf. A lot to discuss!

----

I will send the branch to PR (leaving this issue open for planning). We can continue discussing there. Just an fyi, [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/79#issuecomment-757561111) are the replies to Neil's comments.

FYI @diegogentilepassaro

**Comment by diegogentilepassaro** [comment]
Find my comments here

https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:5a0f6abc-4d76-4758-b4ca-3c1dedc39028

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro! Happy to discuss those open points in our next meeting. Btw, if you want to make changes to the paper (or revise the changes @gabrieleborg and I implemented) you can take a look at PR #88

**Comment by santiagohermo** [comment]
I wrapped up PR #88 @gabrieleborg @diegogentilepassaro. Following Jesse's comments, some stuff we want to try after improving our pipeline are the following:

- Predict number/share of MW workers in each zipcode
- To visualize zillow data, make "scatterplot of annual changes across MSAs or similar, since the national time series is not that informative."
- Update data section of paper
  - Discuss placement of RAC/WAC LODES data
  - Discuss what sectors to show in descriptive table
- About the sectors we use as controls, mention the share of the sectors' workers who are MW earners (on top of mentioning the share of total MW workers who work there).
- Other updates to paper to discuss
  - Do we want to use the cumulative effect to compute heterogeneity? Maybe an efficient version of it using only two lags?
  - Similarly, do we want to use the cumulative effect for the benchmarking?
  - Should we appendix the Arellano-Bond model?
  - Should we drop heterogeneity based on median income in table 5?
  - Make maps of residuals of statutory and experienced MW regressions. This involves outputting a dataset after running regressions that contains predicted values and residuals.

**Comment by santiagohermo** [comment]
Superseded by #107. Closing @diegogentilepassaro @gabrieleborg
