### ISSUE TITLE
Explore new controls/robustness following Leung (2020)

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#80]
**Goal**
Improve our specification by refining the choice of controls and choice of events (anticipated or not)

**Steps**
1. Read and understand what Leung (2020) does
2. Assess and locate additional data sources we may need

**Comment by gabrieleborg** [comment]
Hi guys @diegogentilepassaro @santiagohermo! 

I reviewed the Leung (2020) 
- His main goal is to study the MW pass-through to prices. Specifically, he focuses on retail prices by using the Nielsen data. 
- Notably, he uses the same paper we use to get most of the MW changes, so we are using similar events (besides the last years). 
- He finds that a 10 percent increase in MW leads to a .6 percent increase in prices, and he finds that pass-through for other store types is not significant. He also finds that the pass-through elasticity in grocery stores in poor counties is higher than what you would expect from a purely labor shock cost (i.e. demand is fixed and supply shifts). 
- He then uses sufficient statistics to understand the determinants of MW pass-through elasticity. He derives different pass-through formulas by assuming different things, and comparing those with his results. 
- How firms, and workers react to MW changes? Who ends up paying? He identifies 3 channels that may lead to higher prices (that is what he documents): 
    - Cost pass-through: holding demand fixed, MW raises labor cost and this translates to higher prices. This however cannot fully explain the magnitude of the price increase. 
    - Demand-side pass-through: 2 channels: 1)increase in income lead to an outward shift in demand; 2) income shock have a direct impact on demand elasticity
    - He derives the elasticity formulas and estimate them using the data. 
 
My main conclusion is that his work is related to ours in a good way (similar data, similar approach), but we fundamentally ask different questions: he's researching the impact on the product market, we're looking at the impact on the housing market (also through price). In this sense we are advantaged because there are less channels that may affect prices: I feel it's easier for us to assume fixed supply in the housing market. 

In terms of data, he uses **Nielsen** data at the place-quarter. If we want to expand our work to keep track of other pass-through then we could think about accessing such data ([here](https://www.chicagobooth.edu/research/kilts/datasets/nielsen) we can apply). However, I think that if our goal is to properly pin down the magnitude of the pass-through to the housing market, we need to understand how MW affect households consumption, saving and employment beyond grocery spending only. To do this, we may want to look at credit card data (e.g. [Facteus](https://www.facteus.com)). In this sense, I feel another useful thing would be to focus on clarifying the employment effect of MW. He also refers to Dube et al. and using QWI data he shows increase in earning but not employment. a potential source for individual payslips data is [Homebase](https://joinhomebase.com) (they have a form to apply for research data, even though it may be related to COVID projects only). 

As for other census-related data, similarly to us he uses QWI data at the county level. The additional controls he uses come from ACS and LAUS but I don't see how they may add anything in our framework since we use monthly variation. 

One potential expansion could be LAUS data (Local Area Unemployment Statistics), that comes at the county-month level. However, county-level data are inferred by state-level variation using population weights from the census:
<img width="1192" alt="Screen Shot 2021-01-18 at 5 12 08 PM" src="https://user-images.githubusercontent.com/30894427/105064973-5b8dd180-5a4b-11eb-891f-38ae1209e71c.png">

**Comment by diegogentilepassaro** [comment]
Thanks for this awesome summary @gabrieleborg! What do you think that are the outstanding things before we close? If it is effortless, should we add and download population and unemployment or something like that?

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro, 

I think that in the light of what Leung did, and what we discussed on Jan 19th 2021, we could do the following: 

1. download population and unemployment data
2. Add a reference to this paper in the draft

I would say that after these two things we can close this issue and, once we updated the repo according to #82 , we can then start updating the analysis with the downloaded new data. 

What do you think guys? After that I would close this issue

**Comment by diegogentilepassaro** [comment]
That sounds awesome @gabrieleborg!

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! I'm on board with that plan as well :)

**Comment by gabrieleborg** [comment]
ok @santiagohermo @diegogentilepassaro, I will first review #82 because it's more connected to other work we have to do, and after that I will close this, which is a more standalone task!

**Comment by gabrieleborg** [comment]
Thread continues in #84
