### ISSUE TITLE
First attempt on a serious model

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#81]
In this issue I will start thinking about a potential model for the paper. 

Notes:
- See Jesse's guidelines in https://github.com/diegogentilepassaro/min_wage_rent/issues/79#issuecomment-756338280
- Old toy model available in `analysis/notes`

**Comment by santiagohermo** [comment]
Paper to cite: [Manning and Petrongolo (2017)](https://www.aeaweb.org/articles?id=10.1257/aer.20131026). It shows that labor markets are quite local, making it important to focus on small geo units

**Comment by santiagohermo** [comment]
I'll use this comment to collect what seem relevant papers.

### Urban Models

- [Ahlfeldt et al (2015). The Economics of Density: Evidence From the Berlin Wall](https://www.princeton.edu/~reddings/pubpapers/Berlin-Ecta-10876.pdf). Model of residence-workplace choice within a city that is located in some wider economy. The within-city choice is defined at the block level, utility is exogenously given by the country, and firms choose location as well. There is a housing sector that determines residence vs office space. 
- [Monte, Redding and Rossi-Hansberg (2018). Commuting, Migration, and Local Employment Elasticities](https://www.aeaweb.org/articles?id=10.1257/aer.20151507). Explores the determinants of _local employment elasticities_. Writes down model of residence-workplace choice that includes a goods market ("We develop a spatial general equilibrium model in which locations are linked in goods markets through trade and in factor markets through migration and commuting".)
- [Jorge Perez (2020). City Minimum Wages](https://jorgeperezperez.com/files/Jorge_Perez_JMP.pdf). Builds an urban model with 3 types of workers who get to choose where they live and work. There is a representative firm in each location endowed with a CES production function. There is also a matching technology for each location (so unemployment), and a housing market.

### Min wage Effects

- [Bhaskar, Manning and To (2002). Oligopsony and Monopsonistic Competition in Labor Markets](https://www.aeaweb.org/articles?id=10.1257/0895330027300). Argues that oligopsony can explain low disemployment effects.
- [Aaronson and French (2007). Product Market Evidence on the Employment Effects of the Minimum Wage](https://www.jstor.org/stable/10.1086/508734?seq=10#metadata_info_tab_contents). Early example of theoretical discussion of employment effects for different industrial structures (and empirical estimation)
- [Azar et al (2019). Minimum Wage Employment Effects and Labor Market Concentration](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3416016). Empirical paper showing that employment effects are smaller (and even _positive_) for more concentrated labor markets.
- [Leung (2020). Minimum Wage and Real Wage Inequality: Evidence from Pass-Through to Retail Prices](https://www.mitpressjournals.org/doi/abs/10.1162/rest_a_00915?mobileUi=0). Estimates the pass-through of MW increases to retail prices.

**Comment by diegogentilepassaro** [comment]
@santiagohermo thanks for organizing this, is pretty great. One question other question that just came to my mind when reading your posts: What is the relevant local labor market in our model? Is it the case that there are $m$ labor markets in the US (say metropolitan areas or some unified commuting zone), and then within each of those there are $J_m$ locations that represent zip codes, or you are thinking as if the local labor market is directly the zip code? If the former, why different firms are located in different zipcodes? is that exogenous? If the latter, have you seen some example of that in another paper?

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro! I would say that it's option A: "there are $m$ labor markets in the US (say metropolitan areas or some unified commuting zone), and then within each of those there are $J_m$ locations that represent zip codes". I'm writing the model as if there is a single metropolitan area with some exogenous level of population. We would have to think about how to incorporate multiple metropolitan areas later.

Regarding firms location. This sounds like a hard problem which I didn't want to get into. Thus, I assumed one representative firm per zipcode. We basically want some wage in $i$ that workers working in $i$ earn, so that when we set a MW it transmits through commuting. Alternative approaches can be found in the the papers listed [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/81#issuecomment-762337695):
- Monte et al (2018) similarly assumes firms located in each location $i$. However, they assume varieties as in [Dixit-Stiglitz](https://en.wikipedia.org/wiki/Dixit%E2%80%93Stiglitz_model). We could potentially incorporate this.
-   Gaubert (2018) is an example that deals with firm location. I don't think we should go down this road

**Comment by diegogentilepassaro** [comment]
This all sounds good @santiagohermo! Thanks 👍

**Comment by santiagohermo** [comment]
Hi @diegogentilepassaro @gabrieleborg. In [this commit](https://github.com/diegogentilepassaro/min_wage_rent/commit/0c68e879cdb7514671a7f1b206d9ed92114013f9) (mistagged) I wrote down a document that extends our benchmarking model to a geography with many zip codes. [This](https://github.com/diegogentilepassaro/min_wage_rent/blob/0c68e879cdb7514671a7f1b206d9ed92114013f9/analysis/notes/benchmark_multiple_locations.pdf) is the pdf.

It's is sort of a simple way of writing out our intuition that, because the MW in workplace increases income in ZIP code $i$, but a MW in residence lowers income, then experienced and statutory MW will tend to have opposite effects. The idea of the more complicated model, I think, would be to add microfundaments to something similar to the "extended benchmarking". What do you think?

Btw, if you want to help out thinking about the model, I strongly recommend [Monte, Redding, and Rossi-Hansberg (2018). Commuting, Migration, and Local Employment Elasticities](https://www.aeaweb.org/articles?id=10.1257/aer.20151507). See also [Online Appendix](https://assets.aeaweb.org/asset-server/files/8471.pdf), which contains a lot of useful proofs (including a model with several skill types, from which we may want to copy some more stuff).

**Comment by santiagohermo** [comment]
A few ideas based on discussion today with @diegogentilepassaro, @gabrieleborg.

I updated the simple model [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/ef68aa14bf3508f77b199e3f1f2feef0f293626a/analysis/notes/benchmark_multiple_locations.pdf). This is very stylized and makes it clear why the experienced MW may have a different effect relative to the statutory one. A model in this fashion could be used as "theoretical framework" to motivate the paper, and have a proposition that says "Under assumption x, y, and z, the experienced MW increases rents in a zipcode and the statutory MW lowers them".

@diegogentilepassaro agreed on thinking about a model in the spirit of the other one I was writing before, although simpler. (With the intention of possibly computing some notion of welfare) We discussed with Diego that it'd be nice to have a couple of simple models as alternatives, show them to Jesse and Neil (and someone else possibly), check whether they think they'll make an interesting addition, and decide whether to include them or not from there.

I think that a full-blown quantitative model is something to work on in a follow-up project :). Let me know what you think @gabrieleborg !

**Comment by santiagohermo** [comment]
In the above commit I added a proposal to motivate the experienced MW @diegogentilepassaro @gabrieleborg. See [this pdf](https://github.com/diegogentilepassaro/min_wage_rent/blob/d6e815e0c1daf7e8c309c069df13142878524cb5/issue81/model_proposal.pdf).

This is very simple and simply illustrates the spillover of income across ZIP codes, which is kind of the mechanism we have in mind. They key assumption is that workplace MW increase disposable income, whereas residence MWs lower it. We could try to complicate it a bit by adding local goods consumption or something that justifies that assumption. However, as I said [before](https://github.com/diegogentilepassaro/min_wage_rent/issues/81#issuecomment-764832401) I think that a full-blown model is probably an undertaking worthy of a new project.

Talk to you soon!

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg I have started an overleaf document to keep the model work going with what we discussed last time. @santiagohermo and I showed it to Neil in the BReakfast and he thought it was interesting, although our aim now should be to have a basic document to show to Jesse and discuss the next steps. 

https://www.overleaf.com/project/6011e2221cd9783d12536d10

**Comment by santiagohermo** [comment]
Per today's call, I will wrap up the simple model here and send it to PR. We want to talk to some professors to understand if it's a good idea to include it in the paper. If yes, we would restructure the paper to make the experienced MW more of an integral part of it.

We also want to continue developing a more detailed model. We are leaning towards leaving this for a future project though.

**Comment by santiagohermo** [comment]
Continues in PR #91

**Comment by santiagohermo** [comment]
Final code for model proposal [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/defd77d780c7aba67d18e0782f37a27be54a8b04/issue81/model_proposal.Rmd). Pdf [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/defd77d780c7aba67d18e0782f37a27be54a8b04/issue81/model_proposal.pdf) in the future when writing this down somewhere.
