### ISSUE TITLE
Apply Geo Master Crosswalk in Base

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#87]
**Goal**
Update `base`'s scripts so to uniformly use the new `geo_master` dataset. 

This issue is part of the pipeline updating #85. Once done, merge back to branch `#85-pipeline`.

_UPDATE_: See plan for updated pipeline [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/85#issuecomment-774740656). In this issue the main goal is to update `lodes` to output origin-destination matrices. Splitting MW and Zillow stays confined to #86.

**Comment by gabrieleborg** [comment]
Hi @santiagohermo and @diegogentilepassaro! 

I am posting here the initial updates to`base` where we start applying the new geo_master xwalk. As I told you, I will come back to work on this tuesday night/wednesday morning (Feb 10th), so I will try to explain in as much details as I can what I did so far, in case you want to pick up something. 

So far I have split the folder `base/zillow_min_wage` in two: `base/zillow` and `base/min_wage`. 

**`base/zillow`** 
- here we now have only one file, [`base/zillow/code/RenameZillowVars_ziplevel.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/apply-geomaster-base/base/zillow/code/RenameZillowVars_zipLevel.R). This file didn't need any update since it doesn't use any crosswalk, but it simply format Zillow data that are already at the zip code level. 

**`base/min_wage`**
- Here I moved 4 files: 
    - [`substate_mw.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/apply-geomaster-base/base/min_wage/code/substate_mw.do): nothing to update here since it simply creates substate level mw datasets (one county and one local)
    - [`state_mw`](https://github.com/diegogentilepassaro/min_wage_rent/blob/apply-geomaster-base/base/min_wage/code/state_mw.do): same here
    - [`cleanGeoRelationshipFiles.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/apply-geomaster-base/base/min_wage/code/cleanGeoRelationshipFIles.R): we are not using this script anymore since all the crosswalk between geos are already addressed in `geo_master`. However, I decided to leave it here _temporarily_. This is becasue I didn't finish to update other `base` folders (e.g. `bps`, `demographics`) and I don't remember whether there are dependencies with output of such script. Once we update everything and we are sure, we can delete it. Same logic for dependencies in `derived`. 
    - [`make_mw_panel_zip.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/apply-geomaster-base/base/min_wage/code/make_mw_panel_zip.R): I modified this script - that we were previously using for bulding the experience mw - by using output from `geo_master`. 
        - Note that the old way we used to assembled mw here was the same we (still) use in [`derived/zipcode_month/code/addMinWage.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/apply-geomaster-base/derived/zipcode_month/code/addMinWage.R). Now we won't need that part anymore since we will have both zillow and mw datasets alreadt at the zip code level
        - The main issue was to assign zip codes to counties starting from the new master xwalk: 
            - First, I kept (USPS) zip code - county pair with the most number of houses
            - 36 zip codes had duplicates: mostly zip codes assigned to both a city (with a place code) and to rural area (with place code 99999). In this case I assigned the zip code to the city. 
            - Compared to the old method, we gained 129 new zip codes
            - Before merging with local MW, I manually went through each local MW place name and manually fixed any inconsitency with the placenames reported in the master xwalk (e.g. We had Daly City and Daly city). Here is when I discovered the Emeryville/Oakland issue. After listening to your replies, I think a safe option is to keep things as they are by simply assigning the zip code to the place with more houses. We can think more about that. 

Again, sorry for not updating more as of now. What's left in this task is therefore: 
- finish checking (and potentially updating) the remaing folders in `base`
- check that any dependency in `derived` (and `analysis`?) are updated in the light of the new `base` structure (e.g. the input strings that may still have `base/zillow_min_wage`)

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! That looks great as a first pass. Does it make sense to you if I bring those changes to the branch for #86, and we use this issue with a new branch to update other folders? So that we can later review those steps separately.

**Comment by santiagohermo** [comment]
Hi @gabrieleborg. I organized branches and stuff a little bit.

- Per [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/85#issue-794627143), I will work on separating MW and Zillow construction in #86. I already started building on your changes discussed [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/87#issuecomment-773476349) in the branch `#86-pipeline_zillow_min_wage` (see https://github.com/diegogentilepassaro/min_wage_rent/issues/86#issuecomment-774566487)
- In this issue we should focus on applying the geo_master in other steps in `base`
  - Note that, in [this commit](https://github.com/diegogentilepassaro/min_wage_rent/commit/8e7c012baf83268cfbb6e2a7b0369d24ab6cf69b), I added the geo_master csv in the branch for #85 
  - After that, I created a branch `#87-pipeline_geomaster_base` for this task.

**Comment by gabrieleborg** [comment]
Hi @santiagohermo and @diegogentilepassaro !

I'm sorry I haven't been able to reply sooner, i rushed too much before leaving for Seattle, and didn't realize that part was already assigned..my bad

Thanks for reorganizing, I'll get back to my laptop Tuesday night and get back to speed.!

**Comment by santiagohermo** [comment]
No problem @gabrieleborg, thanks! Sorry for bothering you so much while you are visiting Seattle haha

**Comment by santiagohermo** [comment]
Per call @gabrieleborg will focus on updating LODES, and @santiagohermo and @diegogentilepassaro will review other steps in `base` to check whether they need updating

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro @santiagohermo, I updated the LODES script! 

Originally, the `base/lodes/code/` folder contained 3 files: `make_lodes_ziplevel.R`, `make_odmatrix_ziplevel.R`, and `make_lodes_experienced_ziplevel.R`. 

- `make_lodes_ziplevel.R`: I left the file as it is, and it still lives in [`base/lodes/code/`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2387-pipeline_geomaster_base/base/lodes/code). This script creates already a zip code month-level panel of residence and workplace statistics (i.e. workers count, for different types of workers). We use this to proxy for the number of min wage residents and workers. Note that here we _don't_ use the origin-destination matrix at all (i.e. we know neither where the residents work nor where the workers live). Rather, we use a LODES specific crosswalk (made up of multiple files stored in `raw/crosswalk/lodes/`) to aggregate block-level statistics to tracts, and then the tract-usps zip code crosswalk that is not part of the geo-master. For this reason, I thought that - in the spirit of the repo re-organization principle- we should leave this in `base` where we output simple zip code month-level panels (such as the zillow one). I changed only one thing, that is I updated the tract-zip code crosswalk from the 2012 version to the 2019 version, the last year of our sample. This would allow us not to lose potential zip code that in the zillow data appears after 2012 (even though I suspect are very few). 
- `make_odmatrix_ziplevel.R`: Here the same reasoning applies. We don't use any geography present in the geo-master, so I didn't need to update it. The reason is that also here the original matrix comes at the block level so to produce a final usps zip code level origin-destination matrix we only need the LODES-specific crosswalk, and the tract-usps zip crosswalk. I also left this in `base/lodes/code`.
-  `make_lodes_experienced_ziplevel.R`: Here is where the new geo_master crosswalk was needed. However, I ended up deleting this script and integrating it with [`derived/min_wage/code/make_mw_panel_zip.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2387-pipeline_geomaster_base/derived/min_wage/code/make_mw_panel_zip.R) since more than half of it was identical. I know this is technically out of the scope of the issue (updating `base`), but as I needed to remove the original script, I had to place some of its functions somewhere. The reason integrated them is that, in order to compute the expereinced mw we basically need 2 ingredients: the od matrix created by `make_odmatrix_ziplevel.R`, and the zip code month-level mw panel of statutory mw. The crosswalk updating part was related to building the latter, and @santiagohermo already placed it in `derived/min_wage/code`, so I updated that file. Basically I extended it so that after building the classic mw panel, we use the odmatrix to build the experienced measure, and we add them all together in a final mw panel. This is stored in `drive/derived_large/output`. you can look at logs and file_manifest at [`derived/min_wage/output`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2387-pipeline_geomaster_base/derived/min_wage/output).
    - A question related to this is: Do you want me to keep updating this script to compute the log values that we discussed last time? That sounds like a different issue but I wanted to hear your opinion :)

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! Your decisions look good to me. About moving `make_lodes_experienced_ziplevel.R` to `derived/min_wage` that sounds good! I'd say we take a look again when we are working on that step, but knowing that it works for now is great (I never tried the previous scripts I copied there).

To wrap up the `base/lodes` task, could you do the following? Change the output folder to `drive/base_large/lodes` and make a fresh run with python (I already did this with zillow, with files being saved in `drive/base_large/zillow`). I'm going for eventually deleting `drive/base_large/output`, since it's kind of messy to have all files together. Also, we would like to delete files in the drive folder before running from `make.py`, and we can't do that if they live mixed with other steps in `drive/base_large/output`.

I'll hopefully be able to make a pass on other `base` steps soon, and we can move to PR :)

**Comment by santiagohermo** [comment]
I just made a pass on `alt_rents` in `base`. I simplified the code somewhat and changed the name of the folder to `safmr` (since we actually clean those data there) fyi @gabrieleborg @diegogentilepassaro

**Comment by gabrieleborg** [comment]
Thanks @santiagohermo, I changed the output dir to `drive/base_large/output/lodes` and run the python script. Let me know if I can help you in finishing re-viewing something in `base` too.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! Your changes in `lodes` look good.

> Let me know if I can help you in finishing re-viewing something in `base` too.

That would actually be very useful. I think we need to take a look at `bps`, `demographics` and `qcew`. If you have time, could you do the following?

- quickly review code and, if possible, simplify. If there are things we don't use anymore (nor plan to use in the future), drop
- make sure that output in `drive` gets saved to `base_large/STEP` rather than `base_large/output`
- make a clean run of the step and add output to drive
- Add brief readme like [this](https://github.com/diegogentilepassaro/min_wage_rent/blob/93ff31c79f136d5835eabf2c3757d4ec467fc833/base/min_wage/README.md) one? (We would like to know if we need to run other folders before completing a given step)

Once we are done with this, I think we can move to PR. I'd be happy to review

**Comment by diegogentilepassaro** [comment]
Thanks for all of this @gabrieleborg and @santiagohermo! Once you finish iterating send this to PR and I'll review all the changes and test with some fresh runs :D

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro I reviewed `bps`, `demographics`, `qcew`. There were no major changes to do, I created `drive/base_large/STEP` folders and added `README.md` files.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! That looks good.

I noticed that, e.g. in demographics, the output goes to `drive/base_large/output/demographics`. On the other hand, I was before using `drive/base_large/zillow` (without the "output"). I'm indifferent in which way is better, but I think they should all look the same. After harmonizing that, let's go to PR!

**Comment by gabrieleborg** [comment]
@santiagohermo done! now the folders live directly in `base_large` :)

**Comment by santiagohermo** [comment]
Continues in #94
