### ISSUE TITLE
Create new main datasets for the zipcode and county level

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/min_wage_rent#89]
[Goal]
Create `derived/zipcode` and `derived/county` to produce datasets restricted to the Zillow sample (of either zipcodes or counties) that contains rents, MW, and other variables such as those from QCEW and the experienced MW.  We will use the output from `base/zillow`, `derived/min_wage` and from other folders needed to include demographics and QCEW data.

[Notes]
- We will want to output each of the datasets at the monthly, quarterly, and yearly levels. Note that this implies thinking about how to collapse monthly medians to the quarterly or yearly level.

**Comment by santiagohermo** [comment]
#102 open for this. Closing @diegogentilepassaro
