### ISSUE TITLE
Build MW variables in `derived/min_wage`

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#92]
In this issue we will update the step `derived/min_wage` in the pipeline. This step will use the output from
- `base/geo_master`,
- `base/min_wage`, and
- `base/lodes`

to construct a series of MW measures for the entire US. In particular, we want to output two datasets (one at the zipcode and other at the county level, both with monthly frequency) that contain the following MW vars:

- actual mw: maximum between city, county, and state levels,
- actual mw excluding city ordinances,
- experienced MW, i.e., `sum_{i \in Z} \pi_{ni} MW_{i}` for each zipcode `n`, where `pi` are lodes weights and `MW_{i}` is the actual mw,
- log of above variables,
- experienced log MW, i.e., `sum_{i \in Z} \pi_{ni} log MW_{i}`

This task is tracked in #85. As such, it will branch off of `issue85-pipeline` and later merge back there.

**Comment by santiagohermo** [comment]
I envision the structure as follows:

- `build_statutory.R/do` constructs MW measures for both geographies as max of city, county and state levels
- `build_experienced.R/do` constructs experienced MW from output of step above, and creates a new dataset at the zipcode level with experienced MW measures.

Happy to discuss in the call tomorrow!

**Comment by santiagohermo** [comment]
One comment here @diegogentilepassaro @gabrieleborg. I noticed while taking a look at the code in #93 that, to build the exp mw, we do the following:

- compute exp_mw by state
- paste all states

Does this take into account commuters to other states? I guess not? Could we account for them in the code by first putting the entire matrix together or something?

**Comment by gabrieleborg** [comment]
Hey @santiagohermo !

The script already takes care of out-of-state workers. This is done by the `aux` files that are merged together and added to each state matrix ;)

**Comment by santiagohermo** [comment]
Thanks for the quick reply,@gabrieleborg! I hadn't noticed those files, that's great.

**Comment by gabrieleborg** [comment]
thanks @santiagohermo for the review, it looks good to me!

yes, let's look at the experienced MW in the call :)

**Comment by santiagohermo** [comment]
Wait for geo_master to have unique zip code-zcta combination. Build experienced.

Other things to do:
- Fix name of county dataset
- Keep whole US

**Comment by santiagohermo** [comment]
Note: branch updated from `issue85` after fixing geo_master in #96

**Comment by santiagohermo** [comment]
Continues in #100
