### ISSUE TITLE
Prepare slides for Applied Micro Lunch

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#93]
In this issue we will create slides for the Applied Micro Lunch presentation, to be held on February 23.

The idea is to:
- Use results from previous version of draft
- Show a brief version of the model to gauge reactions

**Comment by diegogentilepassaro** [comment]
Task received @santiagohermo!

**Comment by gabrieleborg** [comment]
@diegogentilepassaro I modified `base/lodes/code/make_lodes_experienced_ziplevel.R`. Now we compute the sum of the logs. I already checked in `derived` and there's nothing to change, BUT once you re-run the analysis you should slightly modify the `preclean.do` files since there we still take the logs of, among other variables, the exp mw. I didn't change it because you guys are going to re-run the analysis and therefore I think it's better that you address the naming convention once you have a clearer idea of what to do there :) 

Let me know if everything is clear!

**Comment by santiagohermo** [comment]
En el commit above updateé `lodes` en esta branch @diegogentilepassaro. 

Let's remember that, in this branch, lodes computes the experienced mw. Now, it computes the alternative measure of the `experienced log MW` we talked about. The [data_file_manifest](https://github.com/diegogentilepassaro/min_wage_rent/commit/9362f494fa83f09f933e2efcde33db3566706686#diff-0bb8ad19946370176624e245d34bf603653331ffdce4210b8fafc1ddd533359b) seems quite sensible. I copied the resulting dataset `../../../drive/base_large/output/exp_mw.dta` in the Google Drive, so it should update soon.

**Comment by santiagohermo** [comment]
Some ideas after the practice:

- Don't talk on each other | Each use the slides.
- Shorter Data?
- Fix identification. Shorten?
- Shorter text. Stop more in important stuff.
- Double "+" in model.
- Fix "magnitude of effects" slide (Cegniz, parenthesis, number of digits).
- Average share of people who work in different ZIP code?

**Comment by diegogentilepassaro** [comment]
@santiagohermo also really important because it helps understand the model more mundanely and because it maps with the empirical strategy that follows let's move model after data!

**Comment by gabrieleborg** [comment]
Thanks a lot @santiagohermo and @diegogentilepassaro for this effort! Slides looks very good now!

I have added few comments [here](https://github.com/diegogentilepassaro/min_wage_rent/files/6026690/long_slides_GB.pdf). They are mostly stylistic adjustments, so if you decide to change them it won't take you more than 5 minutes, but be sure to check the pass-thorugh table because there was a weird number in my opinion.

**Comment by diegogentilepassaro** [comment]
We presented and the slides are [here](https://github.com/diegogentilepassaro/min_wage_rent/files/6031141/min_wage_rent.pdf)!

Also, JP Colombia pointed to [this cool paper](https://pubs.aeaweb.org/doi/pdfplus/10.1257/aer.20171445).

@santiagohermo, when you are ready send the video :D

**Comment by santiagohermo** [comment]
Thanks @diegogentilepassaro ! [Here](https://brown.zoom.us/rec/play/h9fn-lzOKvo1c39Uynv9fbLMdMN8cc5v-hFF004UMIf9i9BLTdDWXMndbWYTGN2UzyxXucg0xFLU99tm.uHdcLHeJK8N1wRz4) is a link to the video. (Need to be logged in [brown zoom](brown.zoom.us) to enter)

**Comment by santiagohermo** [comment]
Another nice paper proposed by JP colombia [here](https://www.nber.org/system/files/working_papers/w26295/w26295.pdf)
fyi @diegogentilepassaro @gabrieleborg

**Comment by santiagohermo** [comment]
Some papers recommended by Neil some time ago (I found an old email by @diegogentilepassaro with these 😮):

https://www.aeaweb.org/articles?id=10.1257/pol.20150176

https://scholar.harvard.edu/files/ran/files/search.pdf

**Comment by santiagohermo** [comment]
Matt says to connect to more to place-based policy literature.

https://www.annualreviews.org/doi/full/10.1146/annurev-economics-080213-041024

https://eml.berkeley.edu/~pkline/papers/PBR_2021.pdf

**Comment by santiagohermo** [comment]
A paper about uniform-pricing.

https://eml.berkeley.edu/~sdellavi/wp/uniform-pricing.pdf

**Comment by diegogentilepassaro** [comment]
Also another two:

https://eml.berkeley.edu/~pkline/papers/PBR_2021.pdf

https://www.annualreviews.org/doi/full/10.1146/annurev-economics-080213-041024

**Comment by santiagohermo** [comment]
I'm closing this task @gabrieleborg @diegogentilepassaro 

- To avoid conflicts, I copied and pasted the slides directly to master in this commit.
- I deleted the branch `#93-slides-lunch`
  - Final state of branch is [here](https://github.com/diegogentilepassaro/min_wage_rent/tree/306588a3f8b94480fa53799d9e88917933bd7c25)
  - In particular, the updated code that produces the figures is [here](https://github.com/diegogentilepassaro/min_wage_rent/tree/306588a3f8b94480fa53799d9e88917933bd7c25/analysis/first_differences_expmw/code). This will be recycled after we finish #85
