### ISSUE TITLE
Improve model

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#95]
We received a lot of feedback on the model (from slides in #93) recently. In this issue, we will attempt to update the model based on that feedback.

- One approach is to base the model on bargaining. The slides below show a potential way (modelling the bargaining between firms and workers)
  https://economics.mit.edu/files/20576

- A second approach is to build on the demand idea, but add vacancies on the supply side and some people who has to match to those vacancies in the given month on the demand side. This would allow for moving within ZIP codes more explicitly. Slides below may be useful (one way to model search)
  https://economics.mit.edu/files/20579

**Comment by santiagohermo** [comment]
Handbook chapter [here](https://www-2.rotman.utoronto.ca/facbios/file/HS_Handbook_Microstructure_8-29-2014.pdf): _The Microstructure of Housing Markets: Search, Bargaining, and Brokerage_

**Comment by santiagohermo** [comment]
Another potentially useful resource may be ["Lectures on Labor Economics"](https://economics.mit.edu/files/4689) by Acemoglu and Autor

**Comment by santiagohermo** [comment]
Can we know how many people rent a house in the same zip code, say year by year, @diegogentilepassaro @gabrieleborg? That may be useful to know to justify our model assumptions

**Comment by santiagohermo** [comment]
I'll open up a branch in which I'll start to modify the paper in this branch @diegogentilepassaro @gabrieleborg. I'll update the model section, and maybe add some placeholders for analysis we know we'll do after #85.

**Comment by santiagohermo** [comment]
Code from previous model [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/defd77d780c7aba67d18e0782f37a27be54a8b04/issue81/model_proposal.Rmd)

**Comment by santiagohermo** [comment]
About this:

> I'll open up a branch in which I'll start to modify the paper in this branch @diegogentilepassaro @gabrieleborg. I'll update the model section, and maybe add some placeholders for analysis we know we'll do after #85.

This paper might be useful: [The Effects of Rent Control Expansion on Tenants, Landlords, and Inequality: Evidence from San Francisco](https://www.aeaweb.org/articles?id=10.1257/aer.20181289)

Check if we can find some number there.

**Comment by santiagohermo** [comment]
Mistagged commit [here](https://github.com/diegogentilepassaro/min_wage_rent/commit/85faf64b44d1e282c5a374a21c646dfcbdd761da)

**Comment by gabrieleborg** [comment]
hey @santiagohermo @diegogentilepassaro !

Thanks @santiagohermo for the model update! I left here a few comments and syntax-related notes in case you want to have a look before the meeting: 
[model_flows_GB.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/6271642/model_flows_GB.pdf)

Talk soon

**Comment by santiagohermo** [comment]
Jesse's reactions @gabrieleborg @diegogentilepassaro :

- Wrap up the paper (can spend one's life changing the model). Decide//converge
- Need more assumptions to connect with empirical model
- Disposable income --> be more explicit there. JMS would make the one change of adding labor market
- Clustering: https://www.jstor.org/stable/2109724?seq=1
- Conley s.e.: http://www.trfetzer.com/conley-spatial-hac-errors-with-fixed-effects/
- JLE/JUE

**Comment by santiagohermo** [comment]
Did you also understand Journal of Labor Economics @gabrieleborg?

**Comment by gabrieleborg** [comment]
Yes, I think so.

**Comment by santiagohermo** [comment]
I'm closing this task @gabrieleborg @diegogentilepassaro. Some conclusions:

- A somewhat complicated version of the model was added [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/95#issuecomment-840524418). I think the set-up was elegant but it seems too complicated to solve.
- A simpler version was added [here](https://github.com/diegogentilepassaro/min_wage_rent/commit/95315cc75e08c356dd1e2a4904b3a44735c67aa3), with an attempt of simulation. The model wasn't working (I guess there was a mistake somewhere, or the functional forms in the simulation where inconsistent with the assumptions somehow). 
  I was however assuming that many things were constant (labor, wages), which made the model somewhat odd. 
- With the goal of closing the paper soon, I think that a general equilibrium model is beyond the scope. I did however learn many things, which I will add in footnotes and so on.

Here is my resulting thinking on how to structure of the model, to be implemented in #100:
- Add usual static model as motivation.
- Add footnote saying how one could derive the housing demand functions from a maximization problem and the assumption that local prices are increasing function of local minimum wage.
- (Optional) Related to point above, mention that another channel of negative effect of statutory MW is decrease in profits of business owners living in the same zip code.
- Stress that goal of the model is understand short-run dynamics. Mention that studying long-run effect with commuting flows allowed to change is beyond the scope, and is a cool area for future research.
- Add appendix on dynamic version of the simple model.
- Add appendix on bargaining version of the simple model.
- Discuss that this approach to study the effect place-based policies could be used for other policies as well that spill-over spatially through workers commuting (any examples come to mind?)

**Comment by santiagohermo** [comment]
Branch `#95-model_paper` was closed. Discussion continues in #109
