### ISSUE TITLE
Update geo_master crosswalk (format tract_zip)

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#96]
**Goal**
Create a stable version of the crosswalk also for geographies smaller than zipcode (i.e. tracts). 

**Steps**
- format tract_zip crosswalk in `base/geo_master`
- update `base` subfolders by using the updated crosswalk

**Comment by gabrieleborg** [comment]
Thread continues in #99

**Comment by santiagohermo** [comment]
Summary [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/85#issuecomment-801214783)
